this._s=this._s||{};(function(_){var window=this;
try{
_.l("ANyn1");
_.iDc={name:"lupa"};_.cw=function(a){_.zn.call(this,a.Ja)};_.B(_.cw,_.zn);_.cw.yb=_.zn.yb;_.cw.Ea=_.zn.Ea;_.cw.prototype.get=function(a,b){return _.Ud(a,b)};_.cw.prototype.isAvailable=function(a){return _.Vc(a)};_.Bn(_.nn,_.cw);
_.n();
}catch(e){_._DumpException(e)}
try{
_.l("WlNQGd");
var tjh=function(a,b,c){this.trigger=a;this.jIa=b;this.tA=c},lM=function(a){_.x.call(this,a.Ja);this.ka=null;this.Ba=[];this.Aa=null;this.prefix="";this.iGa=[].concat(_.Nc(a.controllers.iGa),_.Nc(a.controllers.mbf),_.Nc(a.controllers.C8d));this.menu=this.getRoot().el();this.Da="listbox"===_.yOa(this.menu);this.Ka=new _.Ur(this.Isd,1E3,this);this.yd(this.Ka);ujh(this)},Djh,Bjh;_.B(lM,_.x);lM.Ea=function(){return{controllers:{iGa:"NNJLud",mbf:"hgDUwe",C8d:"tqp7ud"}}};_.k=lM.prototype;_.k.Nle=function(){return this.Aa};
_.k.pyb=function(a){var b=void 0===b?!1:b;(a=this.AV().find(a))&&this.wa(a,b)};_.k.AV=function(){var a=this,b=[].concat(_.Nc(this.Za("NNJLud").toArray())).filter(function(d){return!a.oa(d).Y6a()}),c=_.Ro(this,"tqp7ud").el();c&&b.push(c);return b};_.k.joe=function(){return this.iGa};_.k.Isd=function(){this.prefix=""};
var ujh=function(a){var b=a.AV();_.Pa(b,function(c){var d=a.oa(c);if(d.isSelected()&&d.isEnabled())switch(d.getType()){case 2:vjh(a);d.Vm(!0);a.ka=c;break;case 3:d.Vm(!0);a.Ba.push(c);break;default:d.Vm(!1)}else d.Vm(!1)},a);b=b[0];a.oa(b).izb()&&b.setAttribute("tabindex","0")};
lM.prototype.clearSelection=function(){for(var a=_.Wa(this.AV()),b=a.next();!b.done;b=a.next()){b=this.oa(b.value);if(b.isSelected()&&b.isEnabled())switch(b.getType()){case 2:vjh(this);break;case 3:this.Ba.pop();break;case 1:case 7:case 6:case 4:case 5:break;default:b.getType()}b.Vm(!1)}wjh(this,null)};var vjh=function(a){a.ka&&(a.oa(a.ka).Vm(!1),a.ka=null)};lM.prototype.oa=function(a){return this.iGa.find(function(b){return b.getRoot().el()===a})};
var xjh=function(a,b){return!!a.AV().find(function(c){return c===b})};lM.prototype.wa=function(a,b){b=void 0===b?!1:b;xjh(this,a)&&yjh(this,a,b)};
var yjh=function(a,b,c){var d=a.oa(b);if(d.isEnabled()){wjh(a,b);switch(d.getType()){case 2:var e=a.ka!==b;e&&(vjh(a),a.ka=b,d.Vm(!0));zjh(a,d,e,c);break;case 3:e=!d.isSelected();d.Vm(e);e?a.Ba.push(b):_.Ha(a.Ba,b);zjh(a,d,!0,c);break;case 5:a=a.getRoot().el();_.te(a,_.odd);break;default:zjh(a,d,!1,c)}d.isSelected()}},zjh=function(a,b,c,d){a=a.getRoot().el();_.te(a,_.mdd,new tjh(b,c,d))};_.k=lM.prototype;_.k.Dsd=function(){return this.ka};_.k.Hoe=function(){return this.Ba};_.k.Mle=function(){return this.Aa};
_.k.cEa=function(){var a=this.ka;return a?this.oa(a).getContent():""};_.k.GTb=function(){var a=this.AV()[0];return a?this.Y6(a):null};_.k.qGc=function(a){var b=this.ka;b&&this.Da?a=b:(void 0===a?0:a)?a=(a=_.xa(this.AV()))?this.Y6(a):null:a=this.GTb();return a};
_.k.Y6=function(a){if(6!==this.oa(a).getType())return a;var b=(new _.Uf([a])).find("*").toArray();return(a=[a].concat(b).find(function(c){return _.je(c)&&_.t.Gd(c)&&("menuitem"===c.getAttribute("role")&&c.hasAttribute("tabindex")||_.Tl(c))}))?a:null};_.k.eAa=function(a){a&&!xjh(this,a)||wjh(this,a)};
var wjh=function(a,b,c){c=void 0===c?!1:c;if(b){var d=a.oa(b);if(!d.isEnabled()&&c)return;d.hgc(!0);d.izb()&&b.setAttribute("tabindex","0")}else a.menu.setAttribute("tabindex","0"),a.menu.focus();a.Aa!==b&&a.Aa&&(c=a.oa(a.Aa),c.izb()&&a.Aa.setAttribute("tabindex","-1"),c.hgc(!1));a.Aa=b},Ajh=function(a){a=a.targetElement;for(var b,c;null!=a.el()&&"G-MENU-ITEM"!==(null==(b=a.el())?void 0:b.tagName)&&"G-MENU"!==(null==(c=a.el())?void 0:c.tagName);)a=a.parent();var d;return"G-MENU-ITEM"===(null==(d=
a.el())?void 0:d.tagName)?a.el():null};_.k=lM.prototype;_.k.vze=function(a){var b=Ajh(a);if(b){var c=a.event;(c=c?c.which||c.keyCode:null)&&32===c?this.Bhc(a):yjh(this,b,!0)}};_.k.Esd=function(){null===this.Aa&&wjh(this,this.AV()[0])};_.k.Fsd=function(){var a=this.getRoot().el();_.te(a,_.pdd)};_.k.Gsd=function(){var a=this.getRoot().el();_.te(a,_.qdd);wjh(this,null)};_.k.Hsd=function(a){(a=Ajh(a))&&wjh(this,a,!0)};
_.k.Bhc=function(a){var b=a.event;if(!b||b.ctrlKey||b.metaKey||b.shiftKey||b.altKey)return!1;var c=b.which||b.keyCode,d=!1;if(27===c)return!0;if(40===c||38===c){var e=this.Aa,f=this.AV();e=38===c?e===f[0]:e===f.pop();if(!this.Da||!e){c=40===c;e=Bjh(this,c);var g;c=null!=(g=c?e.shift():e.pop())?g:null;wjh(this,c);_.Cjh(this,this.Aa)}}else if(13===c||32===c&&!this.prefix)this.Aa&&(d=6===this.oa(this.Aa).getType(),yjh(this,this.Aa,!0));else if(_.no(c))this.Ka.start(),g=String.fromCharCode(c),this.prefix===
g?g=Djh(this,!0):(this.prefix+=g,g=Djh(this,!1)),g&&(wjh(this,g),_.Cjh(this,this.Aa));else return!1;a.actionElement.el().contains(b.target)&&(_.Vn(b),d||_.Wn(b));return!1};Djh=function(a,b){return(b?Bjh(a,!0):a.AV()).find(function(c){return a.oa(c).isEnabled()?(c=a.oa(c).getContent(),_.xqa(c,a.prefix)):!1})};
Bjh=function(a,b){var c=a.Aa,d=a.AV().filter(function(e){return _.t.Gd(e)});null===c&&("0"===a.menu.getAttribute("tabindex")||0<d.length&&"0"===d[0].getAttribute("tabindex"))&&(c=b?_.xa(d):d[0]);c&&(a=d.findIndex(function(e){return c===e}),d=_.nba(d,b?-a-1:-a),a=d.findIndex(function(e){return c===e}));return d};_.Cjh=function(a,b){b&&(a.Fa(b),(a=a.Y6(b))&&a.focus())};
lM.prototype.Fa=function(a,b){if(a){var c=_.t.getSize(this.menu);if(c.height<this.menu.scrollHeight){var d=this.menu.getBoundingClientRect().top,e=_.t.getSize(a);d=a.getBoundingClientRect().top-d;var f=e.height/2;d<f?this.menu.scrollTop+=d-f:d+e.height>c.height-f&&(this.menu.scrollTop+=d+e.height-c.height+f);b&&(this.menu.scrollTop+=a.getBoundingClientRect().top-this.menu.getBoundingClientRect().top-Math.floor((c.height-e.height)/2))}}};_.K(lM.prototype,"uYT2Vb",function(){return this.Bhc});
_.K(lM.prototype,"IgJl9c",function(){return this.Hsd});_.K(lM.prototype,"Tx5Rb",function(){return this.Gsd});_.K(lM.prototype,"WOQqYb",function(){return this.Fsd});_.K(lM.prototype,"h06R8",function(){return this.Esd});_.K(lM.prototype,"PSl28c",function(){return this.vze});_.K(lM.prototype,"xpRsNe",function(){return this.GTb});_.K(lM.prototype,"OG2qqc",function(){return this.cEa});_.K(lM.prototype,"kvm28d",function(){return this.Mle});_.K(lM.prototype,"mFs2Sc",function(){return this.Hoe});
_.K(lM.prototype,"Urwwkf",function(){return this.Dsd});_.K(lM.prototype,"J2hPTe",function(){return this.clearSelection});_.K(lM.prototype,"gSmKPc",function(){return this.joe});_.K(lM.prototype,"lSpRlb",function(){return this.AV});_.K(lM.prototype,"mJ60jb",function(){return this.Nle});_.R(_.l9a,lM);
_.n();
}catch(e){_._DumpException(e)}
try{
var XCd,WCd;XCd=function(a,b){var c=_.IA.Ea.document.documentElement,d=c.scrollHeight;a=Math.max(0,Math.min(c.scrollWidth-_.IA.Ea.window.innerWidth,a));b=Math.max(0,Math.min(d-_.IA.Ea.window.innerHeight,b));c.style.height=d+"px";c=_.IA.Ea.document.body.style;c.position="fixed";c.width="100%";c.left=-a+"px";c.top=-b+"px";VCd&&(0,_.an)(VCd);_.IA.Ea.window.requestAnimationFrame?_.IA.Ea.window.requestAnimationFrame(function(){return void WCd(a,b)}):VCd=(0,_.$m)(function(){return void WCd(a,b)},10)};
WCd=function(a,b){_.IA.Ea.window.scrollTo(a,b);VCd=null;_.IA.Ea.document.body.style.position="";_.IA.Ea.document.body.style.width="";_.IA.Ea.document.body.style.left="";_.IA.Ea.document.body.style.top="";_.IA.Ea.document.documentElement.style.height=""};_.IA={};_.IA.Ea={window:window,document:window.document};var YCd=_.ta(),VCd=null;_.IA.by=function(a,b,c){if(a||b)YCd?(c=_.yl(),XCd(c.x+a,c.y+b)):c?_.IA.Ea.window.scrollBy({top:b,left:a,behavior:"smooth"}):_.IA.Ea.window.scrollBy(a,b)};
_.IA.to=function(a,b,c){YCd?XCd(a,b):c?_.IA.Ea.window.scrollTo({top:b,left:a,behavior:"smooth"}):_.IA.Ea.window.scrollTo(a,b)};
}catch(e){_._DumpException(e)}
try{
_.l("U4MzKc");
var ZCd=function(a){_.zn.call(this,a.Ja);this.ka=null;this.window=a.service.window.get();this.document=a.service.window.Gf();this.cache=a.service.cache;this.location=a.service.location;this.storage=this.cache.get("s",_.Zza);this.history=a.service.history;this.oa=this.history.As().listen("FWkcec",function(){})};_.B(ZCd,_.zn);ZCd.yb=_.zn.yb;ZCd.Ea=function(){return{service:{cache:_.cw,history:_.Exc,location:_.Yz,window:_.An}}};_.k=ZCd.prototype;_.k.by=function(a,b,c){(0,_.IA.by)(a,b,c)};
_.k.disable=function(){this.ka||(this.ka=_.Sd(this.document.documentElement,"touchmove",_.Zsa));if(!window.visualViewport||1<=window.visualViewport.scale)this.document.body.style.overflow="hidden"};_.k.enable=function(){this.ka&&(_.Ok(this.ka),this.ka=null);if(!window.visualViewport||1<=window.visualViewport.scale)this.document.body.style.overflow=""};_.k.sre=function(){return this.storage.get(this.location.location.href)};_.k.saveState=function(){this.storage.set(this.location.location.href,_.yl())};
_.k.to=function(a,b,c){(0,_.IA.to)(a,b,c)};_.k.Jb=function(){this.ka&&_.Ok(this.ka);this.oa&&this.history.As().Wt(this.oa)};_.Bn(_.h_a,ZCd);
_.n();
}catch(e){_._DumpException(e)}
try{
_.l("g8nkx");
_.JA=new _.un(_.Yq);
_.n();
}catch(e){_._DumpException(e)}
try{
_.xw=_.J("BUYwVb");_.g_c=_.J("LsLGHf");
}catch(e){_._DumpException(e)}
try{
_.Rad=function(a){var b=_.Pc(a);if(b)return b;b=document.createElement("div");b.id=a;document.body.appendChild(b);return b};_.Kx=function(){return _.Rad("lb")};
}catch(e){_._DumpException(e)}
try{
_.eDd=function(a){_.y.call(this,a)};_.B(_.eDd,_.y);_.fDd=function(a){var b=new _.eDd;return _.vf(b,1,a)};_.eDd.prototype.Ya="mVjAjf";
}catch(e){_._DumpException(e)}
try{
_.LA=function(a,b,c,d,e,f,g,h,m){var r=_.gDd(c),u=_.t.getBounds(a),w=_.t.MJ(a);w&&u.intersection(_.Tya(w));_.t.Jmf(u,_.Ff(a),_.Ff(c));a=_.hDd(a,b);b=u.left;a&4?b+=u.width:a&2&&(b+=u.width/2);u=new _.Zk(b,u.top+(a&1?u.height:0));u=_.bl(u,r);e&&(u.x+=(a&4?-1:1)*e.x,u.y+=(a&1?-1:1)*e.y);if(g)if(m)var A=m;else if(A=_.t.MJ(c))A.top-=r.y,A.right-=r.x,A.bottom-=r.y,A.left-=r.x;return _.iDd(u,c,d,f,A,g,h)};
_.gDd=function(a){if(a=a.offsetParent){var b="HTML"==a.tagName||"BODY"==a.tagName;if(!b||"static"!=_.t.cga(a)){var c=_.t.Zs(a);b||(c=_.bl(c,new _.Zk(_.t.Ii.Hw(a),a.scrollTop)))}}return c||new _.Zk};_.iDd=function(a,b,c,d,e,f,g){a=a.clone();var h=_.hDd(b,c);c=_.t.getSize(b);g=g?g.clone():c.clone();a=_.jDd(a,g,h,d,e,f);if(a.status&496)return a.status;_.t.setPosition(b,_.Xya(a.rect));g=a.rect.getSize();_.Iua(c,g)||_.t.Cbf(b,g);return a.status};
_.jDd=function(a,b,c,d,e,f){a=a.clone();b=b.clone();var g=0;if(d||0!=c)c&4?a.x-=b.width+(d?d.right:0):c&2?a.x-=b.width/2:d&&(a.x+=d.left),c&1?a.y-=b.height+(d?d.bottom:0):d&&(a.y+=d.top);if(f){if(e){g=a;c=b;d=0;65==(f&65)&&(g.x<e.left||g.x>=e.right)&&(f&=-2);132==(f&132)&&(g.y<e.top||g.y>=e.bottom)&&(f&=-5);g.x<e.left&&f&1&&(g.x=e.left,d|=1);if(f&16){var h=g.x;g.x<e.left&&(g.x=e.left,d|=4);g.x+c.width>e.right&&(c.width=Math.min(e.right-g.x,h+c.width-e.left),c.width=Math.max(c.width,0),d|=4)}g.x+c.width>
e.right&&f&1&&(g.x=Math.max(e.right-c.width,e.left),d|=1);f&2&&(d|=(g.x<e.left?16:0)|(g.x+c.width>e.right?32:0));g.y<e.top&&f&4&&(g.y=e.top,d|=2);f&32&&(h=g.y,g.y<e.top&&(g.y=e.top,d|=8),g.y+c.height>e.bottom&&(c.height=Math.min(e.bottom-g.y,h+c.height-e.top),c.height=Math.max(c.height,0),d|=8));g.y+c.height>e.bottom&&f&4&&(g.y=Math.max(e.bottom-c.height,e.top),d|=2);f&8&&(d|=(g.y<e.top?64:0)|(g.y+c.height>e.bottom?128:0));e=d}else e=256;g=e}e=new _.Tm(0,0,0,0);e.left=a.x;e.top=a.y;e.width=b.width;
e.height=b.height;return{rect:e,status:g}};_.hDd=function(a,b){return(b&8&&_.t.Gi(a)?b^4:b)&-9};
}catch(e){_._DumpException(e)}
try{
var MA=function(a){_.x.call(this,a.Ja);var b=this;this.offsetY=this.offsetX=0;this.Aa=!1;this.data=a.jsdata.ehe;this.ka=a.service.dismiss;this.Km=a.service.Km;this.root=this.getRoot().el();this.popup=this.Ca("V68bde").el();_.To(this,this.popup);this.Ba=function(){b.zka()};_.Sd(window,"resize",this.Ba);this.Da=this.rH().hasAttribute("role");this.wa()};_.B(MA,_.x);MA.Ea=function(){return{jsdata:{ehe:_.eDd},service:{dismiss:_.Nx,Km:_.JA}}};_.k=MA.prototype;
_.k.Jb=function(){this.oa()&&this.isVisible()?this.ka.dismiss(this.popup):this.ka.unlisten(this.popup);_.Nk(window,"resize",this.Ba);_.Ye(this.root,this.popup)||this.root.appendChild(this.popup);_.x.prototype.Jb.call(this)};
_.k.onDismiss=function(a,b,c){if((c=void 0===c?null:c)&&_.La(c)&&0<c.nodeType&&_.Ye(this.rH(),c)||a.some(function(d){return _.Ye(d,c)}))return!1;if(_.Bi(this.data,12))return this.trigger(_.dDd,{type:b,Wv:c}),!0;this.setVisible(!1);2===b&&(a=this.rH(),a.hasAttribute("tabindex")||(a=a.firstElementChild),a.focus());return!0};
_.k.Qjd=function(a){var b=this,c=a.event;if(!c)return!1;c=c.which||c.keyCode;40!==c&&38!==c||!this.getPopup().querySelector("g-menu")||(this.Km.disable(),this.PUc(a),(0,_.$m)(function(){b.Km.enable()},0));return!1};_.k.PUc=function(a){var b=a.event||void 0;a.actionElement.el().focus();a=a.data&&a.data.nonDismissingElements||[];this.setVisible(!this.isVisible(),b,this.rH().firstElementChild,a);b&&(b=_.ne(b))&&b.preventDefault()};
_.k.zka=function(){if(this.isVisible()){var a=this.getPopup(),b=this.rH(),c=new _.Zk(this.offsetX,this.offsetY),d=kDd(_.Mb(this.data,1)),e=kDd(_.Mb(this.data,2));if(null===b.offsetParent&&"fixed"!==b.style.position)this.dismiss();else{if(_.Bi(this.data,7)){var f=_.t.getSize(b).width;if(_.Bi(this.data,9)){_.t.Nd(a,"");var g=_.t.getSize(a).width;g>f&&(f=g)}_.t.Nd(a,f)}f=(_.Bi(this.data,5)?1:0)|(_.Bi(this.data,6)?4:0);if((g=window.visualViewport)&&1!==g.scale){var h=_.gDd(this.getPopup());g=new _.Sm(g.pageTop-
h.y,g.pageLeft+g.width-h.x,g.pageTop+g.height-h.y,g.pageLeft-h.x)}else g=void 0;_.LA(b,d,a,e,c,void 0,f,void 0,g)}}};_.k.isVisible=function(){return _.t.Gd(this.getPopup())};_.k.dismiss=function(){this.isVisible()&&this.ka.dismiss(this.popup)};
_.k.setVisible=function(a,b,c,d){var e=this;d=void 0===d?[]:d;var f=this.getPopup(),g=a!==this.isVisible(),h=a?_.aDd:_.bDd;_.t.kb(f,a);a&&_.Ye(this.root,f)?_.Bi(this.data,8)||_.Kx().appendChild(f):a||_.Ye(this.root,f)||this.root.appendChild(f);a&&(this.trigger(_.$Cd,{popup:this}),this.zka());g&&(this.Da&&this.rH().setAttribute("aria-expanded",a?"true":"false"),a?(this.Aa||(this.Aa=!0,_.Te(f,_.xw),_.Te(f,h)),this.oa()?this.ka.listen(this.popup,function(m,r){return e.onDismiss(d,m,r)},[].concat(_.Nc(lDd),
[4]),!1,!0,!1,function(){e.setVisible(a,b,c,d)},this.getData("bbena").string()||this.root.getAttribute("jsname")):this.ka.listen(this.popup,function(m,r){return e.onDismiss(d,m,r)},_.Bi(this.data,10)?mDd:_.Bi(this.data,11)?nDd:lDd,!1,!0)):this.ka.unlisten(this.popup),this.trigger(h,{triggerElement:c||null,V3a:38===(b?b.which||b.keyCode:null)?!0:!1,Lv:b}))};_.k.rH=function(){return this.Ca("oYxtQd").el()};_.k.getPopup=function(){return this.popup};
_.k.zLa=function(a,b){this.offsetX=a;this.offsetY=b};var kDd=function(a){var b=8;switch(a){case 2:b=2;break;case 1:b=8;break;case 3:b=12;break;case 5:b=3;break;case 4:b=9;break;case 6:b=13}return b};MA.prototype.oa=function(){var a=this.getData("bbena"),b=a.string("")||this.root.getAttribute("jsname");return!(!a.Ib()||!b)};MA.prototype.wa=function(){var a=this;this.oa()&&this.ka.Ba(function(){a.setVisible(!0)},this.getData("bbena").string()||this.root.getAttribute("jsname"))};
_.K(MA.prototype,"NjCoec",function(){return this.wa});_.K(MA.prototype,"OOY56c",function(){return this.oa});_.K(MA.prototype,"pcAkKe",function(){return this.getPopup});_.K(MA.prototype,"vBAC5",function(){return this.rH});_.K(MA.prototype,"IYtByb",function(){return this.dismiss});_.K(MA.prototype,"eO2Zfd",function(){return this.isVisible});_.K(MA.prototype,"xKqF2c",function(){return this.zka});_.K(MA.prototype,"WFrRFb",function(){return this.PUc});_.K(MA.prototype,"uYT2Vb",function(){return this.Qjd});
_.K(MA.prototype,"k4Iseb",function(){return this.Jb});_.R(_.o9a,MA);var lDd=[1,2,3],mDd=[1,3],nDd=[1,2];
}catch(e){_._DumpException(e)}
try{
_.l("DPreE");

_.n();
}catch(e){_._DumpException(e)}
})(this._s);
// Google Inc.