this._s=this._s||{};(function(_){var window=this;
try{
_.l("aa");

_.n();
}catch(e){_._DumpException(e)}
try{
_.l("abd");
var k1g=function(a){for(var b="",c=21,d=0;d<a.length;d++)3!=d%4&&(b+=String.fromCharCode(a[d]^c),c++);return b},l1g=function(a){var b=0,c;for(c in a)if(a[c].e)if(a[c].b)b++;else return!1;return 0<b},q1g=function(a){a=void 0===a?{}:a;var b={};b[m1g]={e:!!a[m1g],b:!_.kPd(n1g)};b[o1g]={e:!!a[o1g],b:!_.kPd(p1g)};return b},r1g=function(a){var b=[],c;for(c in a)a[c].e&&b.push(c+":"+(a[c].b?"1":"0"));return b.join(",")},t1g=function(a,b){a=String(a);b&&(a+=","+b);google.log(s1g,a)},u1g=function(a,b,c){c=
void 0===c?2:c;if(1>c)t1g(7,b);else{var d=new Image;d.onerror=function(){u1g(a,b,c-1)};d.src=a}},n1g=k1g([97,119,115,111,107]),p1g=k1g([97,119,115,111,107,123]),v1g=k1g([118,115,121,107,108,124,104,119,68,127,114,105,114]),s1g=k1g([101,126,118,102,118,125,118,109,126]),w1g=k1g([116,116,115,108]),m1g=k1g([113,115,99,107]),o1g=k1g([113,115,117,107]),x1g=k1g([58,127,122,103,121,126,127,98,104,51,109,124,118,123,15,76,81,90,13,95,67,76,64,118]),y1g={};
_.Ee("abd",(y1g.init=function(a){a=void 0===a?{}:a;if(a[w1g]&&_.kPd(v1g)){a=q1g(a);var b=r1g(a);l1g(a)?t1g(1,"0,"+b):t1g(0,b);(0,_.ad)(function(){u1g(x1g,"aa")})}},y1g));
_.n();
}catch(e){_._DumpException(e)}
try{
_.Pyc=function(a,b){b=void 0===b?{}:b;a.details||(a.details={});Object.assign(a.details,b)};_.Qyc=function(a,b){b=(void 0===b?0:b)?_.iBa:_.kBa;for(var c=_.Wa(_.tu),d=c.next();!d.done;d=c.next()){var e=_.Wa(d.value);d=e.next().value;e=e.next().value;b.has(d)&&a.set(d,e)}};_.Ryc=function(a){var b=_.uu();_.fBa.forEach(function(c){var d=b.get(c);d&&a.set(c,d)});_.Qyc(a)};
}catch(e){_._DumpException(e)}
try{
_.vy=function(a,b,c){c=void 0===c?{}:c;a=Error.call(this,a);this.message=a.message;"stack"in a&&(this.stack=a.stack);this.details=c;this.details.t=b};_.B(_.vy,Error);_.Ted=void 0;
}catch(e){_._DumpException(e)}
try{
_.$ed=new _.Am;_.$ed.oa=!0;
}catch(e){_._DumpException(e)}
try{
_.wy=function(a,b){b=(void 0===b?{}:b).priority;this.cacheKey=a;this.priority=b};
}catch(e){_._DumpException(e)}
try{
_.cfd=String(window.google&&window.google.erd&&window.google.erd.bv);_.dfd=new Map;_.Toa("skew",function(){for(var a="",b=!0,c=_.Wa(_.dfd.entries()),d=c.next();!d.done;d=c.next()){var e=_.Wa(d.value);d=e.next().value;e=e.next().value;a+=(b?"":",")+d+"."+e;b=!1}return a});
}catch(e){_._DumpException(e)}
try{
var efd,ifd,lfd,mfd,ofd,qfd,pfd;efd=function(a){return a instanceof Error?a:Error(String(a))};
ifd=function(a,b,c){var d=_.ffd,e,f,g,h,m,r,u,w,A,D,I;_.Fe(function(O){switch(O.ka){case 1:return e=gfd++,f={},d.set(a,(f.si=e,f),"x"),g={values:[],sYc:[],sOb:[]},hfd.set(e,g),_.Dg(O,2,3),_.Ge(O,b.forEach(function(Q){g.values.push(Q);for(var U=_.Wa(g.sYc),ha=U.next();!ha.done;ha=U.next())ha=ha.value,ha(Q)}),5);case 5:for(hfd.has(e)&&(h={},d.set(a,(h.sv=g.values,h),c)),m=_.Wa(g.sOb),r=m.next();!r.done;r=m.next())u=r.value,u();case 3:_.Ig(O);hfd.delete(e);_.Lg(O,0);break;case 2:A=w=_.Hg(O);d.remove(a);
D=_.Wa(g.sOb);for(r=D.next();!r.done;r=D.next())I=r.value,I(A);O.Pb(3)}})};lfd=function(a){var b=_.jfd(_.ffd,a);if(!b)return null;if("sv"in b)return _.kfd(b.sv);if("si"in b){var c=hfd.get(b.si);return new _.xy(function(d,e){for(var f=_.Wa(c.values),g=f.next();!g.done;g=f.next())d(g.value);c.sYc.push(d);c.sOb.push(e)})}throw Error("Le`"+a);};_.jfd=function(a,b){return(a=a.get(b))?a:null};mfd=function(a){return[JSON.parse(a.metadata.serialize()),a.body]};
ofd=function(a){return{metadata:new _.nfd(a[0]),body:a[1]}};_.xy=function(a){var b=this;this.oa=[];this.ka=[];this.closed=!1;this.wa=null;try{a(function(c){if(b.closed)throw Error("Je");if(b.ka.length){var d=b.ka.shift().resolve;d({value:c,done:!1})}else b.oa.push(c)},function(c){pfd(b,c)})}catch(c){pfd(this,efd(c))}};_.kfd=function(a){return new _.xy(function(b,c){for(var d=_.Wa(a),e=d.next();!e.done;e=d.next())b(e.value);c()})};
qfd=function(){var a,b;return{stream:new _.xy(function(c,d){a=c;b=d}),push:a,close:b}};pfd=function(a,b){b=void 0===b?null:b;if(!a.closed){a.closed=!0;a.wa=b;for(var c=_.Wa(a.ka),d=c.next();!d.done;d=c.next()){var e=d.value;d=e.resolve;e=e.reject;b?e(b):d({value:void 0,done:!0})}a.ka.length=0}};
_.xy.prototype.next=function(){var a=this;if(this.oa.length){var b=this.oa.shift();return Promise.resolve({value:b,done:!1})}return this.closed?this.wa?Promise.reject(this.wa):Promise.resolve({value:void 0,done:!0}):new Promise(function(c,d){a.ka.push({resolve:c,reject:d})})};_.xy.prototype.forEach=function(a){var b=this,c,d,e;return _.Fe(function(f){if(1==f.ka)return _.Ge(f,b.next(),5);c=f.oa;d=c.value;return(e=c.done)?f.Pb(0):_.Ge(f,a(d),1)})};
_.xy.prototype.map=function(a){var b=this;return new _.xy(function(c,d){var e;return _.Fe(function(f){if(1==f.ka)return _.Dg(f,2),_.Ge(f,b.forEach(function(g){c(a(g))}),4);if(2!=f.ka)return d(),_.Gg(f,0);e=_.Hg(f);d(efd(e));_.He(f)})})};_.xy.prototype.catch=function(a){var b=this;return new _.xy(function(c,d){var e;return _.Fe(function(f){if(1==f.ka)return _.Dg(f,2),_.Ge(f,b.forEach(function(g){c(g)}),4);if(2!=f.ka)return d(),_.Gg(f,0);e=_.Hg(f);try{a(efd(e)),d()}catch(g){d(efd(g))}_.He(f)})})};
var rfd=function(a){var b=void 0===b?2:b;for(var c=[],d=[],e=[],f=0;f<b;f++){var g=qfd(),h=g.push,m=g.close;c.push(g.stream);d.push(h);e.push(m)}a.forEach(function(r){for(var u=_.Wa(d),w=u.next();!w.done;w=u.next())w=w.value,w(r)}).then(function(){for(var r=_.Wa(e),u=r.next();!u.done;u=r.next())u=u.value,u()},function(r){for(var u=_.Wa(e),w=u.next();!w.done;w=u.next())w=w.value,w(efd(r))});return c};var hfd=new Map,gfd=0;_.nfd=function(a){_.y.call(this,a)};_.B(_.nfd,_.y);_.nfd.prototype.getType=function(){return _.Oi(this,1,0)};_.nfd.prototype.ka=function(){return _.Mb(this,1)};_.nfd.prototype.setType=function(a){return _.vf(this,1,a)};_.nfd.prototype.Ac=function(){return _.gj(this,1)};_.sfd=function(a){_.y.call(this,a)};_.B(_.sfd,_.y);_.sfd.prototype.ka=function(){return _.C(this,1)};var tfd,ufd;_.ffd=_.Kia(_.ba.ka?"n":"s",{name:"async"});tfd=new Map;ufd=function(a,b){this.ka=null;this.oa=a+"__h";this.wa=a+"__r";this.priority=b&&b.priority};_.vfd=function(a,b){var c=b instanceof _.wy?b:void 0;a=a+"__"+(c?c.cacheKey:b);b=tfd.get(a);b||(b=new ufd(a,c),tfd.set(a,b));return b};
ufd.prototype.getResponse=function(){var a=this,b,c,d,e;return _.Fe(function(f){if(1==f.ka)return _.Ge(f,a.ka,2);b=_.ffd.get(a.oa);c=lfd(a.wa);if(!b||!c)return f.return(null);d=new _.sfd(b);e=c.map(ofd);return f.return({header:d,resources:e})})};ufd.prototype.open=function(){var a=this;if(this.ka)return!1;this.ka=new Promise(function(b){a.Aa=b});return!0};
_.wfd=function(a,b,c){var d=b.header,e=b.resources;c=void 0===c?!1:c;if(!a.Aa)return{header:d,resources:e};b=a.priority;var f;(f=_.Jb(d,2))?f!==_.cfd?(_.dfd.set(f,(_.dfd.get(f)||0)+1),f=!0):f=!1:f=!1;f&&!c&&(b="x");e=_.Wa(rfd(e));c=e.next().value;e=e.next().value;_.ffd.set(a.oa,JSON.parse(d.serialize()),b);ifd(a.wa,c.map(mfd),b);a.Aa();a.ka=null;a.Aa=null;return{header:d,resources:e}};
_.xfd=function(a){_.ffd.remove(a.oa);var b=a.wa,c=_.ffd,d=_.jfd(c,b);d&&("si"in d&&hfd.delete(d.si),c.remove(b));a.ka=null;a.Aa=null};
}catch(e){_._DumpException(e)}
try{
var zfd,Cfd;_.yfd=function(a){this.element=a;var b=_.Cf(a,"asyncFc");this.wa=b?_.wc(a,"asyncFc"):null;b&&_.wc(a,"asyncOns");this.jz=b?"callback:"+_.wc(a,"asyncOns"):_.wc(a,"asyncType");this.Aa=b?_.wc(a,"asyncFcv"):null;b=_.wc(a,"graftType");this.pG="none"===b?null:b||"insert";this.oa=_.wc(a,"asyncRclass")||"";this.method=(this.ka=_.wc(a,"asyncToken"))||"stateful"===_.wc(a,"asyncMethod")?"POST":"GET"};
_.yfd.prototype.reset=function(){this.element.textContent="";this.element.removeAttribute("eid");this.setState("yp");delete this.element.__yup;_.Jna()};_.yfd.prototype.setState=function(a){_.En.removeAll(this.element,zfd);_.En.removeAll(this.element,_.Afd);_.En.add(this.element,a);_.yy(this.element,_.Bfd[a])};zfd=["yp","yf","yi"];_.Afd=["yl","ye"];Cfd={};_.Bfd=(Cfd.yp="asyncReset",Cfd.yf="asyncFilled",Cfd.yl="asyncLoading",Cfd.ye="asyncError",Cfd);
}catch(e){_._DumpException(e)}
try{
_.Dfd=function(a,b,c){try{var d=JSON.parse(a)}catch(e){c(),d=void 0}return new b(d)};
}catch(e){_._DumpException(e)}
try{
var Efd,Ffd,Gfd,Hfd,Ifd,Jfd,Kfd;Efd=function(){return _.Lc.apply(0,arguments).reduce(function(a,b){return 0<a&&0<b?Math.min(a,b):0<b?b:a},0)};Ffd=function(a,b,c,d){b=Efd(b||Math.max(document.documentElement.clientHeight,window.innerHeight),d,c);return{src:_.rm(a,"h",b),height:b}};Gfd=function(a,b,c,d){b=Efd(b||Math.max(document.documentElement.clientWidth,window.innerWidth),d,c);return{src:_.rm(a,"w",b),width:b}};Hfd=function(a){var b=_.Eva()||1;return 1<b?_.rm(a,"scale",Math.min(2,b)):a};
Ifd=function(a,b){if(16==(a.ownerDocument.compareDocumentPosition(a)&16)&&!a.src.startsWith("data:")){var c=Gfd(a.src,0,b,a.parentElement&&a.parentElement.clientWidth||0);a.src!==c.src&&(a.onload=function(){a.width=c.width;a.onload=null},a.src=c.src,a.complete&&(a.width=c.width))}};Jfd=function(a){return"0"===a?"":a+"px"};Kfd=function(a){return a?a+"px":""};
_.Lfd=function(a,b){var c=0,d=0;if(a.hasAttribute("data-sp")){var e=a.parentElement&&a.parentElement.clientHeight||0,f=a.parentElement&&a.parentElement.clientWidth||0,g=_.Wa(a.getAttribute("data-sp").split(",").map(function(A){return Math.max(0,Number(A))})),h=g.next().value,m=g.next().value,r=g.next().value,u=g.next().value;b=Ffd(b,h,r,e);d=b.height;f=Gfd(b.src,m,u,f);c=f.width;b=Hfd(f.src);window.addEventListener("resize",_.eh(function(){Ifd(a,u)},100))}if(a.src!==b){var w=new Image;_.Mk(w,"load",
function(){"1"===a.getAttribute("data-deferred")&&a.setAttribute("data-deferred","2");a.src=w.src;if(a.hasAttribute("data-d")){var A=a.getAttribute("data-d").split(",");6===A.length?(a.height=d||Number(A[0]),a.width=c||Number(A[1]),a.style.marginTop=Jfd(A[2]),a.style.marginRight=Jfd(A[3]),a.style.marginBottom=Jfd(A[4]),a.style.marginLeft=Jfd(A[5])):4===A.length&&(a.style.height=Kfd(A[0]),a.style.width=Kfd(A[1]),a.style.marginTop=Kfd(A[2]),a.style.marginLeft=Kfd(A[3]));a.removeAttribute("data-d")}});
w.src=b}};
}catch(e){_._DumpException(e)}
try{
_.Mfd=function(a){_.y.call(this,a)};_.B(_.Mfd,_.y);_.Mfd.prototype.getStringValue=function(){return _.Zi(this,3,_.Nfd)};_.Nfd=[2,3,4,5,6];
}catch(e){_._DumpException(e)}
try{
_.Ofd=function(a){a=_.zka(a);return _.Wpa(a)};_.Pfd=function(a){_.y.call(this,a)};_.B(_.Pfd,_.y);_.Pfd.prototype.getName=function(){return _.C(this,1)};_.Pfd.prototype.Wc=function(a){return _.lf(this,1,a)};var Qfd=function(a){_.y.call(this,a)};_.B(Qfd,_.y);Qfd.prototype.addRule=function(a,b){return _.ri(this,1,_.Pfd,a,b)};Qfd.Qa=[1];var Rfd=_.ac(Qfd);_.Sfd=function(a){_.y.call(this,a)};_.B(_.Sfd,_.y);_.Sfd.Qa=[1];_.Sfd.prototype.Ya="tq7Pxb";var Vfd;_.Tfd={};_.Ufd=null;_.Wfd=function(a){_.Pa(_.mi(a,_.Mfd,1),function(b){"ptnYGd"===_.Jb(b,1)?(b=Rfd(b.getStringValue()),Vfd(b)):_.Tfd[_.C(b,1)]=b})};Vfd=function(a){if(_.Ufd){var b=_.mi(_.Ufd,_.Pfd,1);b=new Set(b.map(function(d){return _.Jb(d,1)}));a=_.Wa(_.mi(a,_.Pfd,1));for(var c=a.next();!c.done;c=a.next())c=c.value,b.has(_.Jb(c,1))||_.Ufd.addRule(c)}else _.Ufd=a};
}catch(e){_._DumpException(e)}
try{
_.Yfd=function(a){_.y.call(this,a)};_.B(_.Yfd,_.y);_.Yfd.Qa=[1];
}catch(e){_._DumpException(e)}
try{
_.Zfd=!0;
}catch(e){_._DumpException(e)}
try{
_.$fd=!1;_.agd=!1;_.bgd=!1;_.cgd=!1;_.dgd=!1;_.egd=!1;_.fgd=!1;_.ggd=!1;_.hgd=!1;
}catch(e){_._DumpException(e)}
try{
var jgd,kgd,lgd;_.igd={TOP:"top",Yxf:"ee",DFf:"mode",orc:"rhs",KDf:"lhs",VLf:"sge",vLf:"stb"};jgd=Object.values(_.igd);lgd=!_.fgd;
_.mgd=function(){var a=void 0===a?!1:a;if(lgd)try{var b=document.querySelector("[data-st-tgt=mode]"),c=document.querySelector("[data-st-cnt=mode]"),d=!(null==b||!b.getAttribute("data-zru")),e=d?b:null==b?void 0:b.querySelector("[jscontroller]");if(b&&e&&b.parentNode!==c){var f=_.t.zy(e),g=f.top+f.bottom;d=d?106:56;var h=(e.getBoundingClientRect().height||d)+g+"px",m=(null==c?0:c.hasAttribute("data-isc"))?"-4px":"2px",r=(null==c?0:c.hasAttribute("data-isc"))?"8px":"6px";_.t.setStyle(c,"min-height",
h);_.t.setStyle(c,"margin-top",m);_.t.setStyle(c,"margin-bottom",r);_.t.setStyle(c,"display","");_.t.setStyle(c,"visibility","visible");var u=_.sl("S5t6pd");u&&_.t.setStyle(u,"display","none");c.appendChild(b)}lgd=!1}catch(w){_.Hc(Error("Ve"))}if(a||!kgd)for(kgd={},a=Array.from(document.querySelectorAll("[data-st-cnt]")),a=_.Wa(a),b=a.next();!b.done;b=a.next())b=b.value,c=_.wc(b,_.ll("st-cnt")),jgd.includes(c)?(kgd[c]&&_.Hc(Error("Te`"+c)),kgd[c]=b):_.Hc(Error("Ue`"+c));return Object.assign({},kgd)};
}catch(e){_._DumpException(e)}
try{
_.ngd=Object.values(_.igd);
}catch(e){_._DumpException(e)}
try{
var ugd,vgd,wgd,xgd,zgd,Agd,Bgd,Fgd,Jgd,Kgd,Lgd,Dgd,Egd,rgd,Igd,Mgd,ygd;_.pgd=function(a){return(_.Zia().hss||{})[a]};_.qgd=function(a){if(a.details){if(429===a.details.s){var b=a.details.rurl;if(_.dEa(b)&&-1<b.indexOf("/sorry/index?"))return b}if(a.details.e)return _.qgd(a.details.e)}};_.sgd=function(a,b){rgd++;_.Ld().Cc("dos","url."+a+",ssrc."+rgd+",target."+b).log()};_.tgd=function(a,b){_.Ld().Cc("dos","solved,url."+a+",target."+b).log()};
ugd=function(a,b){(null==b?0:b.startsWith("data:"))?a.src=b:_.Lfd(a,b)};vgd=function(a,b){var c=document.createElement("script");_.Cha(c,a);google.asc=b;document.body.appendChild(c);google.asc=void 0};wgd=function(a,b,c){c={asyncErr:c};if(b&&(b=_.uja(b,function(e){return _.je(e)&&(e.hasAttribute("jscontroller")||e.hasAttribute("id"))}))){var d=b.getAttribute("jscontroller");d?c.ctrl=d:c.id=String(b.getAttribute("id"))}return"try { "+a+" } catch (e) { google.dl(e, 0, "+JSON.stringify(c)+"); }"};
xgd=function(a,b){for(var c=_.Wa(a.getElementsByTagName("script")),d=c.next();!d.done;d=c.next())d=d.value,d.hasAttribute("type")&&"text/javascript"!==d.getAttribute("type")||vgd(_.Ofd(wgd(d.text,a,"inline")),b)};zgd=function(a,b,c,d,e,f,g,h,m){d=void 0===d?null:d;e=void 0===e?null:e;f=void 0===f?null:f;g=void 0===g?!1:g;return _.Fe(function(r){return _.Ge(r,(new ygd(a,b,c,d,e,f,g,h,m)).apply(),0)})};_.Ay=function(a,b){b=void 0===b?{}:b;return _.de(Agd(new _.yfd(a),b))};
_.By=function(a,b){b=void 0===b?{}:b;a=new _.yfd(a);return!_.En.contains(a.element,"yp")||_.En.contains(a.element,"yl")?_.de(!1):_.de(Agd(a,b))};_.Cgd=function(a,b){b=void 0===b?{}:b;a=new _.yfd(a);b=Bgd(a,null,b,!0);return _.de(b.then(function(){}))};
Agd=function(a,b){var c,d,e,f,g,h;return _.Fe(function(m){switch(m.ka){case 1:Dgd++;c=a.element.__yup=Dgd;d=new _.Yn("async","csi",void 0,{lRc:!1});d.start();d.Cc("astyp",a.jz);var r;(r=b.context)?(r=r.get("arc_id"),r="stev"===r||"mst"===r):r=!1;r&&(d.Cc("trt","st"),b.Mna&&d.Cc("bb","1"));r=d.ka.getStartDate();var u=google.timers.async;null!=r&&u&&u.t&&u.t.atit&&_.Zn(d,"tcdt",r-u.t.atit);e=new _.Ued(d,b.u$);Egd(a,"yl");_.Dg(m,2);return _.Ge(m,Bgd(a,d,b,!1),4);case 4:f=m.oa;if(!b.onReady){m.Pb(5);
break}return _.Ge(m,b.onReady.call(null),6);case 6:if(g=m.oa,void 0!==g&&!g)return a.setState("yp"),m.return(!1);case 5:return _.Ge(m,zgd(c,f,a,d,b.e2b,e,b.cD,b.ETa,b.SUa),7);case 7:if(c!==a.element.__yup)return m.return(!1);a.setState("yf");_.Yed(e);return m.return(!0);case 2:h=_.Hg(m);_.$n(d,"ft");b.u$&&b.u$(d);d.log();if(c!==a.element.__yup)return m.return(!1);Egd(a,"ye");throw h;}})};
Bgd=function(a,b,c,d){var e=_.$ed.delegate().rab.build(a,c,d);b&&(e.Pn=b);return _.$ed.delegate().ys.fetch(e).catch(function(f){var g,h;return _.Fe(function(m){if(1==m.ka){g=_.qgd(f);if(!g)return m.Pb(2);_.sgd(g,a.element.id);return!_.Ted||_.Ted.Ujb?m.Pb(2):_.Ge(m,_.Ted.hWc(g),4)}if(2!=m.ka)return h=m.oa,_.tgd(g,a.element.id),c.Me||(c.Me=new Map),c.Me.set("google_abuse",h),m.return(Bgd(a,b,c,d));throw f;})})};Fgd=function(a){return function(b){var c=_.qgd(b);c&&_.sgd(c,a);throw b;}};_.Cy=function(a){(new _.yfd(a)).reset()};
_.Ggd=function(a,b){b=void 0===b?"":b;var c=new _.yfd(a);b=_.vfd(c.jz,b);b.open();c=new _.sfd;var d=_.Be(a);c=_.lf(c,1,d);_.wfd(b,{header:c,resources:_.kfd([{metadata:(new _.nfd).setType(2),body:a.innerHTML}])})};
Jgd=function(){var a,b,c,d,e,f,g,h;return _.Fe(function(m){if(1==m.ka){a=google.aipf;google.aipf={push:function(){_.Hc(Error("Xe"))}};_.Hgd={};b=_.Wa(a);for(c=b.next();!c.done;c=b.next())d=c.value,_.Hgd[d.id]=d;Igd||(_.afd?Igd=Promise.resolve(_.$ed.delegate()):(_.bfd=new _.cg,Igd=_.bfd.promise));return _.Ge(m,Igd,2)}e=m.oa;f=e.zJe;g=_.Wa(a);for(c=g.next();!c.done;c=g.next())h=c.value,f.gXb(h).catch(Fgd(h.id));_.He(m)})};
Kgd=function(){var a=_.LYa||(_.LYa=new _.MYa);a.resolve||(a.promise=new _.am(function(b){a.resolve=b}));++a.ka};Lgd=function(){var a=_.LYa||(_.LYa=new _.MYa);a.resolve&&0==--a.ka&&(a.resolve(),a.promise=_.de(),a.resolve=null,a.ka=0)};Dgd=0;Egd=function(a,b){_.En.removeAll(a.element,_.Afd);_.En.add(a.element,b);_.yy(a.element,_.Bfd[b])};rgd=0;Mgd=/^[\w-.:]*$/;
ygd=function(a,b,c,d,e,f,g,h,m){this.Da=a;this.response=b;this.target=c;this.Pn=void 0===d?null:d;this.Ba=void 0===e?null:e;this.wa=void 0===f?null:f;this.Aa=void 0===g?!1:g;this.ETa=h;this.SUa=m;this.ka=[];this.oa=!1};
ygd.prototype.apply=function(){var a=this,b;return _.Fe(function(c){switch(c.ka){case 1:Kgd();b=null;if(_.Zfd)return _.Fg(c,7),_.Ge(c,a.response.resources.forEach(function(d){a.ka.push(d);b||(b=(0,_.ad)(function(){google.jslm=9;google.jsla=a.target.jz;Ngd(a);b=null;google.jslm=10;google.jsla=void 0}))}),7);_.Fg(c,4);return _.Ge(c,a.response.resources.forEach(function(d){a.ka.push(d);google.jslm=9;google.jsla=a.target.jz;Ngd(a);google.jslm=10;google.jsla=void 0}),4);case 4:_.Ig(c);Lgd();_.Lg(c,3);
break;case 7:return _.Ig(c),_.Fg(c,10),_.Ge(c,b,10);case 10:_.Ig(c,0,0,1);Lgd();_.Lg(c,11,1);break;case 11:_.Lg(c,3);break;case 3:if(!a.oa&&a.isActive())throw Error("Me");_.Jna();_.He(c)}})};ygd.prototype.isActive=function(){return this.Da===this.target.element.__yup};
var Ngd=function(a){if(a.isActive())for(;a.ka.length;){var b=a.ka.shift();if(2!==b.metadata.ka()||_.uj(b.metadata,2)){if(!a.oa&&4!==b.metadata.ka())throw Error("Ne`"+a.target.jz);Ogd(a,b)}else{if(a.oa)throw Error("Oe`"+a.target.jz);var c=a,d=c.response.header.ka()||"";c.Pn&&(c.Pn.Cc("ei",d),_.$n(c.Pn,"st"),_.Zn(c.Pn,"bs",b.body.length));_.hd(c.target.element,_.Ie(b.body));c.Aa&&xgd(c.target.element,c.SUa);c.wa&&_.Xed(c.wa,c.target.element);c.target.element.setAttribute("eid",d);a.oa=!0}}};
ygd.prototype.Ca=function(a,b){a=_.C(a.metadata,2)||"";if(!Mgd.test(a))throw b=Error("Pe`"+this.target.jz),b.details={id:a},b;b=b(a);if(!b)throw b=Error("Qe`"+this.target.jz),b.details={id:a},b;return b};
var Ogd=function(a,b){switch(b.metadata.ka()){case 1:break;case 2:var c=a.Ca(b,_.Pc);_.hd(c,_.Ie(b.body));a.Aa&&xgd(c,a.SUa);break;case 6:c=a.Ca(b,function(g){return a.target.element.querySelector('[data-async-ph="'+g+'"]')});Pgd(a,b.body,c,a.wa);break;case 3:var d=a.Ca(b,function(g){return _.Pc(g)||a.target.element.querySelector('img[data-iid="'+g+'"]')});d.mDe?requestAnimationFrame(function(){ugd(d,b.body)}):(ugd(d,b.body),d.mDe=!0);break;case 4:vgd(_.Ofd(wgd(b.body,null,"script")),a.SUa);break;
case 7:c=document.createElement("style");c.appendChild(document.createTextNode(b.body));a.target.element.appendChild(c);break;case 5:c=_.Dfd(b.body,_.Yfd,function(){_.Hc(Error("Re`"+b.body.substr(0,100)),{Ke:{l:b.body.length.toString(),t:a.target.jz}})});for(var e=_.Wa(_.mi(c,_.Xfd,1)),f=e.next();!f.done;f=e.next())f=f.value,_.ba.W_jd[f.getId()]=JSON.parse(f.ka());_.Sh(c,_.Sfd,3)&&_.Wfd(_.q(c,_.Sfd,3));break;case 8:c=JSON.parse(b.body);google.xsrf=Object.assign(google.xsrf||{},c);break;case 9:a.Ba&&
a.Ba.call(null,b.body);break;default:_.Hc(Error("Se`"+b.metadata.ka()))}},Pgd=function(a,b,c,d){var e=document.createElement("div");_.hd(e,_.Ie(b));b=a.Aa?Array.from(e.getElementsByTagName("script"),function(g){return g.text}):[];for(var f=document.createDocumentFragment();e.firstChild;)f.appendChild(e.firstChild);a.ETa&&(f=a.ETa(f,c));e=d?Array.from(f.children):void 0;c.parentElement.replaceChild(f,c);b=_.Wa(b);for(f=b.next();!f.done;f=b.next())vgd(_.Ofd(wgd(f.value,c,"rh")),a.SUa);if(d)for(a=_.Wa(e),
c=a.next();!c.done;c=a.next())_.Xed(d,c.value)};var Qgd;_.Rgd=(null==(Qgd=google)?0:Qgd.aipf)?Jgd():Promise.resolve();
}catch(e){_._DumpException(e)}
try{
_.Sgd=function(a){var b=[];a=_.Wa(a);for(var c=a.next();!c.done;c=a.next()){var d=_.Wa(c.value);c=d.next().value;d=d.next().value;b.push(encodeURIComponent(String(c))+":"+encodeURIComponent(String(d)))}return b.join(",")};
}catch(e){_._DumpException(e)}
try{
_.Tgd=function(){return""};_.Ugd=!1;
}catch(e){_._DumpException(e)}
try{
_.Vgd=function(a){if(!arguments.length)return[];for(var b=[],c=arguments[0].length,d=1;d<arguments.length;d++)arguments[d].length<c&&(c=arguments[d].length);for(d=0;d<c;d++){for(var e=[],f=0;f<arguments.length;f++)e.push(arguments[f][d]);b.push(e)}return b};
_.Wgd=function(a,b,c,d,e){b=new _.Wd(b+c);d=_.Wa(d);for(c=d.next();!c.done;c=d.next()){var f=_.Wa(c.value);c=f.next().value;f=f.next().value;b.searchParams.set(c,""+f)}"POST"===a?e=b.toString():(a=b.toString(),(e=_.Sgd(e))&&(a=a+"&async="+e),e=a);return e};_.Ygd=function(a,b){if(""===b)a="/async/"+a;else if("feed_api"===b)a="/feed-api/async/"+a;else if("search"===b)a="/"+b;else throw Error("Ye`"+b);if(!Xgd.test(a))throw Error("Ze`"+a);return a};
_.$gd=function(a,b,c,d,e,f,g,h,m,r,u,w){e=void 0===e?"":e;c=_.Zgd(a,c,e,void 0===f?"":f,void 0===g?"":g,void 0===h?"":h,void 0===m?"":m,!1,r,u,w);a=_.Ygd(a,e);e=_.Tgd(c);return _.Wgd(d,e,a,c,b)};_.ahd=function(a,b,c){if("POST"===a){a=new Map;(c=_.Sgd(c))&&a.set("async",b+","+c);var d=[];a.forEach(function(e,f){return void d.push(f+"="+e)});return d.join("&")}};
_.Zgd=function(a,b,c,d,e,f,g,h,m,r,u){var w=new Map;h&&w.set("pf","y");r&&(w.set("fc",r),u&&w.set("fcv",u));d&&m&&(h=new _.Sc,_.Nga(h,m,d),(d=_.Tc(h))&&w.set("vet",d));f?w.set("ved",f):w.set("ei",e||_.uc());g&&w.set("lei",g);_.Xfa(w,!1,!0);_.Ryc(w);w.set("yv","3");b.forEach(function(A,D){w.set(D,A)});_.bhd(w);google.sxsrf&&w.set("sxsrf",google.sxsrf);"search"===c&&w.set("asearch",a);w.set("cs",document.body.dataset.dt?"1":"0");return w};
_.chd=function(){var a=_.rc("ejMLCd"),b=_.rc("PYFuDc"),c=new Map;a.Ib()&&c.set("X-Geo",a.string());b.Ib()&&c.set("X-Client-Data",b.string());_.Ted&&c.set("X-DoS-Behavior","Embed");a=_.rc("qfI0Zc");a.Ib()&&c.set("X-Search-Ci-Fi",_.um(a));return c};var Xgd;Xgd=/^[a-z0-9-_/]+(callback:\d+)?$/i;_.bhd=function(){};
}catch(e){_._DumpException(e)}
try{
var Shd;
_.Rhd=function(a,b){b=void 0===b?{}:b;var c=b.trigger,d=b.eZ,e=new Map(b.XMa||[]);if(b=_.wc(a,"asyncContextRequired")){b=new Set(b.split(",").filter(function(m){return!e.has(m)&&(d?!d.has(m):!0)}));for(c=c||a;c&&b.size;){var f=_.wc(c,"asyncContext");if(f){f=_.Wa(f.split(";"));for(var g=f.next();!g.done;g=f.next()){var h=g.value.split(":");g=decodeURIComponent(h[0]);h=decodeURIComponent(h[1]);b.delete(g)&&!e.has(g)&&e.set(g,h)}}c=c.parentElement}if(b.size)throw c={},new _.vy("Missing async context",(new _.yfd(a)).jz,
(c.ck=Array.from(b).sort().join(","),c));}return e};_.Thd=function(a,b){var c=void 0===b?{}:b;b=c.eZ;a=_.Rhd(a,{trigger:c.trigger,XMa:c.XMa,eZ:b});b=new Map(b||[]);c=_.Wa(Shd);for(var d=c.next();!d.done;d=c.next())d=d.value,a.has(d)&&(b.has(d)||b.set(d,String(a.get(d))),a.delete(d));return{context:a,Me:b}};Shd=["q","start"];
}catch(e){_._DumpException(e)}
try{
_.Uhd=null;_.Vhd=null;if(google.xjsu){var Whd=_.Cc(google.xjsu);_.Uhd=_.pm(google.xjsu,"ver")||_.Dc(Whd,"k");_.Vhd=_.oya(Whd)};
}catch(e){_._DumpException(e)}
try{
var Zhd,did,fid,gid,hid;_.Xhd=function(a){return!a||a instanceof Map?new Map(a||[]):new Map(Object.entries(a))};Zhd=function(a,b){if(a){for(var c=[],d=0;d<b.attributes.length;++d){var e=b.attributes[d];e.name in Yhd||c.push(e.name)}_.Pa(c,function(f){b.removeAttribute(f)});c=_.Wa(Object.keys(a));for(d=c.next();!d.done;d=c.next())d=d.value,b.setAttribute(d,a[d])}};_.$hd=function(){return(new _.Yn("async")).start()};
did=function(a,b){var c,d,e,f,g,h,m,r;return _.Fe(function(u){switch(u.ka){case 1:return _.Dg(u,2),_.Ge(u,_.$ed.delegate().ys.fetch(a),4);case 4:return c=u.oa,a.Pn&&(d=c.header.ka())&&(a.Pn.Cc("ei",d),b.setAttribute("async-ei",d)),e=[],_.Ge(u,c.resources.forEach(function(w){var A,D,I,O,Q,U,ha,ia;return _.Fe(function(fa){switch(fa.ka){case 1:switch(w.metadata.ka()){case 1:break;case 2:a.Pn&&_.Zn(a.Pn,"bs",w.body.length);e.push(w.body);break;case 4:A=document.createElement("script");_.Cha(A,_.Ofd(w.body));
D=document.createElement("div");D.appendChild(A);e.push(D.innerHTML);break;case 5:I=_.Dfd(w.body,_.Yfd,function(){return _.Hc(Error("nf`"+w.body.substr(0,100)),{Ke:{l:""+w.body.length,t:a.jz}})});f=_.mi(I,_.Xfd,1);g=_.Sh(I,_.Sfd,3)?_.q(I,_.Sfd,3):void 0;break;case 8:O=JSON.parse(w.body);h=Object.assign(h||{},O);break;case 9:break;case 6:case 3:throw Error("of");case 11:return fa.Pb(2);default:_.Hc(Error("Se`"+w.metadata.ka()))}fa.Pb(0);break;case 2:return Q=_.Dfd(w.body,aid,function(){_.Hc(Error("pf"),
{level:0,Ke:{l:""+w.body.length,t:a.jz}})}),_.Dg(fa,4),_.Ge(fa,_.$e(void 0,{service:{renderer:_.MPb}}),6);case 6:return U=fa.oa,_.Ge(fa,U.l3f(Q),7);case 7:ha=fa.oa;e.push(String(_.gd(ha)));_.Gg(fa,5);break;case 4:ia=_.Hg(fa),_.Hc(ia,{level:0,Ke:{l:""+w.body.length,t:a.jz}});case 5:fa.Pb(0)}})}),5);case 5:return a.Pn&&_.$n(a.Pn,"st"),m=new bid(e.join(""),void 0,void 0,f,g,h),cid(m.id,m),u.return(new _.Fy(b.id,m.id));case 2:throw r=_.Hg(u),a.Pn&&(_.$n(a.Pn,"ft"),a.Pn.log()),r;}})};fid=_.ac(_.Sfd);
gid=_.ac(_.Xfd);hid=function(a,b){this.ka=b;this.cache=_.Ud(_.ba.ka?"n":"s",a)};hid.prototype.store=function(a,b){this.cache.set(a,b.serialize())};var cid=function(a,b){_.iid.cache.set(a,b.serialize(),"x")};hid.prototype.get=function(a){if(a=this.cache.get(a))try{return this.ka(a.slice())}catch(b){}return null};hid.prototype.remove=function(a){this.cache.remove(a)};hid.prototype.clear=function(){this.cache.clear()};var jid,kid,rid,Yhd,nid,oid;_.Fy=function(a,b,c){this.containerId=a;this.lBa=b;this.children=c};_.Fy.prototype.serialize=function(){var a=[this.containerId,this.lBa];this.children&&a.push(this.children.map(function(b){return b.serialize()}));return a};_.Fy.prototype.apply=function(a){if(this.containerId){var b=(a||window.document).getElementById(this.containerId);if(!b)throw Error("gf`"+this.containerId);_.iid.get(this.lBa).apply(b)}_.Pa(this.children||[],function(c){c.apply(a)})};
_.Fy.prototype.append=function(a){return jid(this,a,"beforeend")};_.Fy.prototype.prepend=function(a){return jid(this,a,"afterbegin")};
jid=function(a,b,c){var d=_.iid.get(b.lBa),e=_.nl(a.containerId);switch(c){case "afterbegin":c=_.iid.get(a.lBa).prepend(d,e);break;case "beforeend":c=_.iid.get(a.lBa).append(d,e);break;default:throw Error("hf");}cid(c.id,c);d=(a.children||[]).concat(b.children||[]);d=0<d.length?d:void 0;b.children&&_.Pa(b.children,function(f){f.apply()});return new _.Fy(a.containerId,c.id,d)};_.lid=function(a,b){kid(a,function(c){b(c);return!0})};
kid=function(a,b){b(a)&&a.children&&_.Pa(a.children,function(c){kid(c,b)})};_.Fy.prototype.print=function(){throw Error("jf");};var mid=function(a){var b=a[0],c=a[1],d;a[2]&&(d=a[2].map(function(e){return mid(e)}));return new _.Fy(b,c,d)},bid=function(a,b,c,d,e,f){this.html=a;this.attributes=c;this.ka=d;this.oa=e;this.sV=f;(a=b)||(b=nid.get("acti"),a=0,"string"===typeof b&&(b=_.kl(b),isNaN(b)||(a=b)),--a,nid.set("acti",""+a),a=String(a));this.id=a};
bid.prototype.apply=function(a){_.hd(a,_.Ie(this.html));Zhd(this.attributes,a);oid&&pid(a,new Set);this.sV&&(google.xsrf=Object.assign(google.xsrf||{},this.sV));this.oa&&_.Wfd(this.oa);if(this.ka){a=_.Wa(this.ka);for(var b=a.next();!b.done;b=a.next())b=b.value,_.ba.W_jd[b.getId()]=JSON.parse(b.ka())}_.Jna()};
bid.prototype.serialize=function(){var a,b=null==(a=this.ka)?void 0:a.map(function(d){return d.serialize()}),c;for(a=["dom",this.html,this.id,null,this.attributes||null,b||null,null,(null==(c=this.oa)?void 0:c.serialize())||null,this.sV||null];null===a[a.length-1];)a.pop();return a};bid.prototype.append=function(a,b){return qid(this,a,b,"beforeend")};bid.prototype.prepend=function(a,b){return qid(this,a,b,"afterbegin")};
var qid=function(a,b,c,d){var e=Array.from(_.ol("SCRIPT",c)),f=_.Ie(b.html);c.insertAdjacentHTML(d,_.gd(f));oid&&pid(c,new Set(e));e={};a.attributes&&Object.assign(e,a.attributes);if(b.attributes){Object.assign(e,b.attributes);f=_.Wa(Object.keys(b.attributes));for(var g=f.next();!g.done;g=f.next())g=g.value,c.setAttribute(g,b.attributes[g])}a.sV&&(google.xsrf=Object.assign(google.xsrf||{},a.sV));b.oa&&_.Wfd(b.oa);c=a.ka;if(b.ka){f=_.Wa(b.ka);for(g=f.next();!g.done;g=f.next())g=g.value,_.ba.W_jd[g.getId()]=
JSON.parse(g.ka());c=c?c.concat(b.ka):b.ka}_.Jna();a=a.html;"afterbegin"===d?a=b.html+a:"beforeend"===d&&(a+=b.html);return rid(a,void 0,void 0,e,c)},pid=function(a,b){var c=Array.from(_.ol("SCRIPT",a)).filter(function(e){return!b.has(e)}).map(function(e){return e.text});if(0!==c.length){var d=_.Dl("SCRIPT");_.Cha(d,_.Ofd(c.join(";")));a.appendChild(d);_.Ll(d)}};bid.prototype.isEmpty=function(){return!this.html};
rid=function(a,b,c,d,e,f,g,h){return a||b||c||d&&Object.keys(d).length?new bid(a,b,d,e,g,h):_.sid};Yhd={id:!0,"data-jiis":!0,"data-ved":!0,"data-async-type":!0,"data-async-actions":!0,"data-async-context-required":!0};_.sid=new bid("","_e");_.uid=function(a,b){_.tid.store(a,b);_.lid(b,function(c){if(c.containerId){var d=_.iid.get(c.lBa);d?_.iid.store(d.id,d):_.Hc(Error("kf"),{Ke:{k:a,c:c.containerId}})}})};
_.iid=new hid({name:"acta"},function(a){a.shift();a[4]&&(a[4]=a[4].map(function(b){return gid(b)}));a[5]=null;a[6]=a[6]?fid(a[6]):null;return rid.apply(null,a)});_.tid=new hid({name:"actn"},mid);nid=_.Kia("s",{name:"actm"});oid=!0;cid(_.sid.id,_.sid);var vid,wid,zid,Did,Eid,Cid,yid;vid={};wid=(vid.loading="yl",vid.error="ye",vid);_.xid=function(a){this.element=a;var b=_.Cf(a,"asyncFc");this.type=b?"callback:"+_.wc(a,"asyncOns"):_.wc(a,"asyncType")||"";if(!this.type)throw a=Error("lf"),_.Hc(a),a;this.ka=b?_.wc(a,"asyncFc"):null;this.oa=b?_.wc(a,"asyncFcv"):null;a=_.wc(a,"graftType");this.pG="none"!==a?a||"insert":null};_.xid.prototype.getState=function(){return Array.from(_.En.get(this.element)).map(function(a){return yid[a]}).find(_.$g)};
_.xid.prototype.setState=function(a){zid(this,a);"filled"===a&&_.Pa(this.element.querySelectorAll("."+_.Aid.inlined),function(b){zid(new _.xid(b),"filled")})};_.Bid=function(a,b){_.En.removeAll(a.element,Object.values(wid));""!==b&&(_.En.add(a.element,wid[b]),a.dispatchEvent(b))};zid=function(a,b){_.En.removeAll(a.element,Object.values(_.Aid));_.En.add(a.element,_.Aid[b]);_.Bid(a,"");a.dispatchEvent(b)};_.xid.prototype.dispatchEvent=function(a){_.yy(this.element,Cid[a])};Did={};
_.Aid=(Did.preload="yp",Did.filled="yf",Did.inlined="yi",Did);Eid={};Cid=(Eid.preload="asyncReset",Eid.filled="asyncFilled",Eid.loading="asyncLoading",Eid.error="asyncError",Eid);yid=_.vfa(_.Aid);_.Fid=_.vfa(wid);var Gid=function(a){_.y.call(this,a)};_.B(Gid,_.y);Gid.prototype.ka=function(){return _.q(this,_.Of,2)};var aid=function(a){_.y.call(this,a)};_.B(aid,_.y);aid.prototype.getId=function(){return _.C(this,1)};aid.prototype.Gc=function(a){return _.lf(this,1,a)};aid.prototype.Jd=function(){return _.ej(this,1)};aid.prototype.Ed=function(){return _.q(this,Gid,2)};_.Hid=function(a,b,c,d,e,f){e=void 0===e?{}:e;this.target=a;this.Pn=c||_.$hd();this.Pn.Cc("astyp",a.type);this.trigger=d;this.ka="stateful"===_.wc(a.element,"asyncMethod")||_.wc(a.element,"asyncToken")?"POST":"GET";this.oa=_.wc(a.element,"asyncRclass")||"";this.Tfa=f;try{var g=_.Xhd(b),h=_.Xhd(e),m={trigger:this.trigger,XMa:g,eZ:h};var r=""===this.oa?{context:_.Rhd(this.target.element,m),Me:h}:_.Thd(this.target.element,m);var u=r.context,w=this.target.element;w.id!==this.target.type&&u.set("_id",
w.id);var A=_.wc(this.target.element,"asyncToken");A&&u.set("_xsrf",A);u.set("_pms",_.Vhd);var D=r.Me;this.context=r.context;this.Aa=D}catch(I){this.wa=I}};_.Hid.prototype.fetch=function(){return this.wa?_.bm(this.wa):this.sendRequest()};
_.Hid.prototype.sendRequest=function(){this.context.set("_fmt","pc");var a=_.vc(this.target.element),b=google.getEI(this.target.element),c=this.trigger?_.vc(this.trigger):void 0,d=this.trigger&&google.getLEI(this.trigger)||void 0;a=_.$gd(this.target.type,this.context,this.Aa,this.ka,this.oa,a,b,c,d,this.target.pG,this.target.ka,this.target.oa);b=_.ahd(this.ka,this.target.type,this.context);a={method:this.ka,url:a,F3b:b,Pn:this.Pn,jz:this.target.type,headers:_.chd(),Tfa:this.Tfa};return _.de(did(a,
this.target.element))};
}catch(e){_._DumpException(e)}
try{
var Djd,Ejd,Fjd,Hjd,Gjd,Jjd,Kjd,Ljd,Ijd;Djd=function(a){a=_.wc(a,"asyncTrigger");return document.getElementById(a)};Ejd=function(a){return _.Cf(a,"asyncTrigger")};Fjd=function(){_.Pa(document.querySelectorAll("."+_.Aid.inlined),function(a){(new _.xid(a)).setState("filled")})};Hjd=function(a,b,c,d){var e=_.$hd();return Gjd(a,e,b,c,d)};
Gjd=function(a,b,c,d,e){var f=Ijd(a,b,c,d,e);_.Bid(f.target,"loading");return f.fetch().then(function(g){g.apply();f.target.setState("filled");g=new _.Ued(b);_.Xed(g,f.target.element);_.Yed(g)}).then(void 0,function(g){_.Bid(f.target,"error");throw g;})};
Jjd=function(a,b,c,d,e,f,g){return Ijd(a,b,c,d,e,g).fetch().then(function(h){f?f(b):b.log();return h}).catch(function(h){var m=_.qgd(h);if(m){var r=a instanceof Element?a.id:a.element.id;_.sgd(m,r);if(_.Ted&&!_.Ted.Ujb)return _.Ted.hWc(m).then(function(u){_.tgd(m,r);var w=e,A=new Map;w&&(A=_.Xhd(w));A.set("google_abuse",u);e=w=Object.fromEntries(A);return Jjd(a,b,c,d,e,f)})}throw h;})};Kjd=function(a){_.Hc(a,{Ke:a.details})};
Ljd=function(){_.ye("async",{u:function(a){a=a.actionElement.el();Hjd(a).then(void 0,Kjd)}});Fjd()};_.Mjd=function(a){return Array.from(_.En.get(a.element)).map(function(b){return _.Fid[b]}).find(_.$g)||""};_.Njd=function(a){a=Ejd(a)?Djd(a):a;if(!a)throw a=Error("mf"),_.Hc(a),a;return new _.xid(a)};Ijd=function(a,b,c,d,e,f){if(_.je(a)){var g=_.Njd(a);Ejd(a)&&(d=a)}else g=a;return new _.Hid(g,c||{},b,d,e,f)};_.Jy={};_.Jy.isTrigger=Ejd;
_.Jy.Gja=function(a,b,c,d){var e=_.$hd(),f=_.Njd(a);return"preload"!==f.getState()||"loading"===_.Mjd(f)?_.de():Gjd(a,e,b,c,d)};_.Jy.update=Hjd;_.Jy.append=function(a,b,c,d){var e=_.$hd(),f=Ijd(a,e,b,c,d);_.Bid(f.target,"loading");return f.fetch().then(function(g){(new _.Fy(g.containerId,_.sid.id)).append(g);f.target.setState("filled");g=new _.Ued(e);_.Xed(g,f.target.element);_.Yed(g)}).then(void 0,function(g){_.Bid(f.target,"error");throw g;})};
_.Jy.fetch=function(a,b,c,d,e,f){var g=_.$hd();return Jjd(a,g,b,c,d,e,f)};_.Jy.reset=function(a){a=Ejd(a)?Djd(a):a;_.Cy(a)};_.Jy.Oo=Kjd;_.Jy.init=Ljd;var Ojd={};_.xka("async",(Ojd.init=Ljd,Ojd));
}catch(e){_._DumpException(e)}
try{
var zQd,AQd,CQd,BQd,yQd;
zQd=function(a){var b=a.method,c=a.url,d=a.F3b,e=a.jz,f=a.headers,g=a.Pn,h=_.$c(),m=yQd?yQd():new _.Er;m.listen("complete",function(r){r=r.target;if(r.Lq()){_.$n(g,"st");var u=r.Ww();_.Zn(g,"bs",u.length);if(!u){var w={};h.reject(new _.vy("Async response error",e,(w.s=r.getStatus(),w.r=u,w)))}h.resolve(u)}else _.$n(g,"ft"),g.log(),(u=r.getStatus())?(w={},u=(w.s=u,w),7===r.U7&&(u.ab=1),h.reject(new _.vy("Async request error",e,u))):h.reject(new _.vy("Async network error",e))});a=h.promise.Sp(function(r){if(r instanceof
_.Ic)m.abort();else throw r;});_.$n(g,"fr");m.setWithCredentials(_.Ugd);f=f?Object.fromEntries(f):void 0;m.send(c,b,d,f);return a};AQd=function(a){return!a||a instanceof Map?new Map(a||[]):new Map(Object.entries(a))};_.yB=function(a,b,c,d,e,f,g){g=void 0===g?{}:g;var h=void 0===h?"insert":h;var m=void 0===m?!1:m;var r=BQd(a);r.start();b=AQd(b);g=AQd(g);return CQd(a,b,g,r,"",e,c,void 0,d,f,h,m)};
_.DQd=function(a,b,c,d){d=void 0===d?{}:d;var e=BQd(a);e.start();b=AQd(b);d=AQd(d);return CQd(a,b,d,e,"search",c)};
CQd=function(a,b,c,d,e,f,g,h,m,r,u,w){w=void 0===w?!1:w;b.set("_fmt",w?"json":"jspb");null!=f&&c.set("q",f);b=_.$gd(a,b,c,"GET",e,g,h,m,r,u);return zQd({method:"GET",url:b,Pn:d,jz:a,headers:_.chd()}).then(function(A){A.startsWith(")]}'\n")&&(A=A.substr(5));try{var D=JSON.parse(A)}catch(I){return _.bm(I)}return _.La(D)&&(D=_.pfa(D),A=D.__err__,void 0!==A)?_.bm(A):w||D instanceof Array?_.de(D):_.bm()})};BQd=function(a){var b=new _.Yn("async");b.Cc("astyp",a);return b};yQd=null;
}catch(e){_._DumpException(e)}
try{

_.Zfd=!1;
}catch(e){_._DumpException(e)}
try{

_.hgd=!0;
}catch(e){_._DumpException(e)}
try{
_.Dy=function(a){_.Zg.call(this);this.Ba=1;this.wa=[];this.Aa=0;this.ka=[];this.oa={};this.Da=!!a};_.Wg(_.Dy,_.Zg);_.Dy.prototype.subscribe=function(a,b,c){var d=this.oa[a];d||(d=this.oa[a]=[]);var e=this.Ba;this.ka[e]=a;this.ka[e+1]=b;this.ka[e+2]=c;this.Ba=e+3;d.push(e);return e};_.Dy.prototype.unsubscribe=function(a,b,c){if(a=this.oa[a]){var d=this.ka;if(a=a.find(function(e){return d[e+1]==b&&d[e+2]==c}))return this.unsubscribeByKey(a)}return!1};
_.Dy.prototype.unsubscribeByKey=function(a){var b=this.ka[a];if(b){var c=this.oa[b];0!=this.Aa?(this.wa.push(a),this.ka[a+1]=function(){}):(c&&_.Ha(c,a),delete this.ka[a],delete this.ka[a+1],delete this.ka[a+2])}return!!b};
_.Dy.prototype.publish=function(a,b){var c=this.oa[a];if(c){for(var d=Array(arguments.length-1),e=1,f=arguments.length;e<f;e++)d[e-1]=arguments[e];if(this.Da)for(e=0;e<c.length;e++){var g=c[e];mhd(this.ka[g+1],this.ka[g+2],d)}else{this.Aa++;try{for(e=0,f=c.length;e<f&&!this.isDisposed();e++)g=c[e],this.ka[g+1].apply(this.ka[g+2],d)}finally{if(this.Aa--,0<this.wa.length&&0==this.Aa)for(;c=this.wa.pop();)this.unsubscribeByKey(c)}}return 0!=e}return!1};
var mhd=function(a,b,c){_.Rva(function(){a.apply(b,c)})};_.Dy.prototype.clear=function(a){if(a){var b=this.oa[a];b&&(b.forEach(this.unsubscribeByKey,this),delete this.oa[a])}else this.ka.length=0,this.oa={}};_.Dy.prototype.getCount=function(a){if(a){var b=this.oa[a];return b?b.length:0}a=0;for(b in this.oa)a+=this.getCount(b);return a};_.Dy.prototype.Bc=function(){_.Dy.Rd.Bc.call(this);this.clear();this.wa.length=0};
}catch(e){_._DumpException(e)}
try{

var shd=function(a,b,c){var d=c.body,e=c.contentType,f=c.vCc,g=c.withCredentials,h=c.mXa,m=c.headers;return new _.xy(function(r,u){var w=new XMLHttpRequest;w.open(a,b);w.withCredentials=!!g;void 0!==d&&w.setRequestHeader("Content-Type",e||"application/x-www-form-urlencoded;charset=utf-8");if(void 0!==m)for(var A=_.Wa(m),D=A.next();!D.done;D=A.next()){var I=_.Wa(D.value);D=I.next().value;I=I.next().value;w.setRequestHeader(D,I)}var O=h?h.length:0;w.onreadystatechange=function(){if(!(w.readyState<XMLHttpRequest.HEADERS_RECEIVED)){if(w.readyState===
XMLHttpRequest.HEADERS_RECEIVED){var Q;if(Q=w.responseURL)Q=w.responseURL,Q=(_.nm(b)||location.origin)!==(_.nm(Q)||location.origin);if(Q){u(new nhd("HTTP redirect error",b,w.responseURL));w.abort();return}f&&f.publish("YNQrCf")}if(_.iQa(w.status))O<w.responseText.length&&(r(w.responseText.substring(O)),O=w.responseText.length),w.readyState===XMLHttpRequest.DONE&&(ohd(),u());else if(w.status||!phd)u(new qhd("HTTP error",w.status,w.responseURL)),w.abort()}};rhd();w.send(d)})},thd=function(a,b){var c=
{mXa:")]}'\n"};c=void 0===c?{}:c;var d=c.vCc,e=c.mXa;return new _.xy(function(f,g){var h=e?e.length:0,m=XMLHttpRequest.UNSENT,r=!1,u=function(){if(a.readyState<m)throw Error("$e");a.readyState>=XMLHttpRequest.OPENED&&m<XMLHttpRequest.OPENED&&(m=XMLHttpRequest.OPENED,a.readyState<XMLHttpRequest.DONE&&(rhd(),r=!0));if(!(a.readyState<XMLHttpRequest.HEADERS_RECEIVED)){if(a.readyState>=XMLHttpRequest.HEADERS_RECEIVED&&m<XMLHttpRequest.HEADERS_RECEIVED){m=XMLHttpRequest.HEADERS_RECEIVED;var w;if(w=a.responseURL)w=
a.responseURL,w=(_.nm(b)||location.origin)!==(_.nm(w)||location.origin);if(w){g(new nhd("HTTP redirect error",b,a.responseURL));a.abort();return}d&&d.publish("YNQrCf")}if(_.iQa(a.status))h<a.responseText.length&&(f(a.responseText.substring(h)),h=a.responseText.length),a.readyState===XMLHttpRequest.DONE&&m!==XMLHttpRequest.DONE&&(r&&ohd(),g()),m=a.readyState;else if(a.status||!phd)g(new qhd("HTTP error",a.status,a.responseURL)),a.abort()}};a.readyState!==XMLHttpRequest.DONE&&a.addEventListener("readystatechange",
u);a.readyState>=XMLHttpRequest.UNSENT&&u()})},rhd=function(){1===++uhd&&window.addEventListener("beforeunload",vhd)},ohd=function(){0===--uhd&&window.removeEventListener("beforeunload",vhd)},vhd=function(){phd=!0},whd=function(a){function b(f){var g={};_.Pyc(f,(g.buf=20<c.length?c.substring(0,20)+"...":c,g));return f}var c="",d=0,e=0;return new _.xy(function(f,g){a.forEach(function(h){for(c=c?c+h:h;c;){if(!d){d=1+c.indexOf(";");if(!d)break;if(!/^[0-9A-Fa-f]+;/.test(c))throw b(Error("af"));e=d+parseInt(c,
16)}if(c.length<e)break;f(c.substring(d,e));c=c.substring(e);d=0}}).then(function(){if(c)throw b(Error("bf"));g()}).catch(function(h){return g(h instanceof Error?h:Error(String(h)))})})},zhd=function(a,b,c){var d=a.url,e=a.Me,f=a.Pn,g=a.jz,h=a.Su,m=a.J7,r=a.HM,u,w,A,D,I,O,Q,U,ha;return _.Fe(function(ia){switch(ia.ka){case 1:return _.Ge(ia,xhd(h,g,m,e),2);case 2:u=ia.oa;w=u.F8e;if(A=u.u3d)return f&&_.$n(f,"ttch"),c&&c(),ia.return(A);D=b();_.Dg(ia,3);return _.Ge(ia,yhd(D,g),5);case 5:return I=ia.oa,
_.$ya(d),ia.return(w?_.wfd(w,I,r):I);case 3:O=_.Hg(ia);w&&w.ka&&_.xfd(w);if(O instanceof qhd){Q=O.details.s;U=O.details.rurl;if(Q)throw ha={},new _.vy("Async request error",g,(ha.s=Q,ha.rurl=U,ha));throw new _.vy("Async network error",g);}throw O;}})},yhd=function(a,b){var c,d,e,f;return _.Fe(function(g){if(1==g.ka)return c=whd(a).catch(function(h){var m={};_.Pyc(h,(m.t=b,m));throw h;}),d=Ahd(c).then(function(h){return _.Dfd(h,_.sfd,function(){_.Hc(Error("cf`"+h.substr(0,100)),{Ke:{l:String(h.length),
t:b}})})}),e=Bhd(c,b),_.Ge(g,d,2);f=g.oa;return g.return({header:f,resources:e})})},Bhd=function(a,b){return new _.xy(function(c,d){var e,f;return _.Fe(function(g){if(1==g.ka)return f=e=null,_.Ge(g,a.forEach(function(h){if(!f)if(e){var m={metadata:e,body:h};1===m.metadata.ka()?f=Chd(m,b):10===m.metadata.ka()?google.sxsrf=m.body:c(m);e=null}else e=_.Dfd(h,_.nfd,function(){_.Hc(Error("df`"+h.substr(0,100)),{Ke:{l:String(h.length)}})})}),2);f?d(f):e?d(Error("ef")):d();_.He(g)})})},Chd=function(a,b){var c=
_.Dfd(a.body,Dhd,function(){_.Hc(Error("ff`"+a.body.substr(0,100)),{Ke:{l:String(a.body.length)}})}),d={};d=(d.c=_.Oi(c,1,2),d);(c=_.C(c,2))&&(d.e=JSON.parse(c));return new _.vy("Async server error",b,d)},Ehd=function(a,b){var c=a.req;return zhd(b,function(){return thd(c,a.url)},function(){return void c.abort()})},Ahd=function(a){var b,c,d;return _.Fe(function(e){if(1==e.ka)return _.Ge(e,a.next(),2);b=e.oa;c=b.value;if(d=b.done)throw Error("Ke");return e.return(c)})},Fhd=function(a,b){var c=!1,d=
a.subscribe("YNQrCf",function(e){c||(c=!0,this.unsubscribeByKey(d),b.apply(void 0,arguments))},a)},Ghd=["*","h","m","w","x"],xhd=function(a,b,c,d){var e,f,g;return _.Fe(function(h){switch(h.ka){case 1:e=null;f=a?_.vfd(b,a):null;if(!f){h.Pb(2);break}return _.Ge(h,f.getResponse(),3);case 3:if((e=h.oa)||f.open()){h.Pb(4);break}return _.Ge(h,f.getResponse(),5);case 5:e=g=h.oa;case 4:if(e&&!c){var m=d&&d.has("ved")?d.get("ved"):"",r=_.Om(e.header.ka()).Cc("sqi","17");m&&r.Cc("refv",m);r.log()}case 2:return h.return({F8e:f,
u3d:e})}})};var qhd=function(a,b,c){a=Error.call(this,a);this.message=a.message;"stack"in a&&(this.stack=a.stack);a={};this.details=(a.s=b,a.rurl=c,a)};_.B(qhd,Error);var nhd=function(a,b,c){a=Error.call(this,a);this.message=a.message;"stack"in a&&(this.stack=a.stack);a={};this.details=(a.req=b,a.res=c,a)};_.B(nhd,Error);var phd=!1,uhd=0;var Dhd=function(a){_.y.call(this,a)};_.B(Dhd,_.y);_.afd=!0;
_.Cm(_.$ed,{ys:{fetch:function(a){return zhd(a,function(){var b=a.method,c=a.url,d=a.F3b,e=a.Pn,f=a.headers,g=a.Tfa,h=new _.Dy(!0);Fhd(h,function(){e&&_.$n(e,"ttfb");g&&g()});return shd(b,c,{body:d,vCc:h,withCredentials:_.Ugd,mXa:")]}'\n",headers:f})})}},rab:{build:function(a,b,c){b.context=new Map(b.context);var d=b.context;var e=_.mfa({_ck:window._ck||google.xjs.ck},Boolean);e=new Map(Object.entries(e));_.mka(d,e);var f=void 0===b.context?new Map:b.context,g=void 0===b.Me?new Map:b.Me,h=b.trigger;
d=b.Su;var m=b.JPb;e=b.Tfa;b=b.HM;c=void 0===c?!1:c;f=new Map([].concat(_.Nc(f)));f.set("_fmt","prog");f.set("_id",a.element.id);a.ka&&f.set("_xsrf",a.ka);var r=_.vc(a.element),u=_.Be(a.element),w=h?_.vc(h):void 0;h=h&&_.ika(h)||void 0;g=new Map(g);m&&g.set("ddii","1");m=_.Zgd(a.jz,g,a.oa,r||"",u||"",w||"",h||"",c,a.pG,a.wa,a.Aa);g=_.Ygd(a.jz,a.oa);h=_.Tgd(m);r=_.Wgd(a.method,h,g,m,f);u=_.ahd(a.method,a.jz,f);return{method:a.method,url:r,F3b:u,hostname:h,path:g,Me:m,Gm:f,jz:a.jz,Su:d,headers:_.chd(),
J7:c,Tfa:e,HM:b}}},zJe:{gXb:function(a){var b=a.cp;b=b&&Ghd.includes(b)?b:void 0;return Ehd(a,{method:"GET",url:a.url,jz:a.at,Su:new _.wy(a.ck,{priority:b})})}}});var Hhd;null==(Hhd=_.bfd)||Hhd.resolve(_.$ed.delegate());
}catch(e){_._DumpException(e)}
try{
_.l("async");




_.n();
}catch(e){_._DumpException(e)}
try{
var pwd,qwd,rwd,wwd,twd,uwd,vwd;_.owd=function(a,b,c){a[b]=c};pwd=function(a,b){var c=_.yua(a.ownerDocument&&a.ownerDocument.defaultView);c&&a.setAttribute("nonce",c);a.src=_.kd(b)};rwd=[];_.swd=function(a){if(!a.length)return _.Ke(null);var b=rwd.length;_.Ka(rwd,a);if(b)return qwd;a=rwd;var c=function(){var d=a.shift();d=_.$z(d);a.length&&_.Qm(d,c,c);return d};return qwd=c()};
_.$z=function(a,b){var c=b||{};b=c.document||document;var d=_.sf(a),e=(new _.Yua(b)).createElement("SCRIPT"),f={j0c:e,vY:void 0},g=new _.Je(twd,f),h=null,m=null!=c.timeout?c.timeout:5E3;0<m&&(h=window.setTimeout(function(){uwd(e,!0);g.hF(new vwd(1,"Timeout reached for loading script "+d))},m),f.vY=h);e.onload=e.onreadystatechange=function(){e.readyState&&"loaded"!=e.readyState&&"complete"!=e.readyState||(uwd(e,c.Wwc||!1,h),g.callback(null))};e.onerror=function(){uwd(e,!0,h);g.hF(new vwd(0,"Error while loading script "+
d))};f=c.attributes||{};_.kc(f,{type:"text/javascript",charset:"UTF-8"});_.vl(e,f);pwd(e,a);wwd(b).appendChild(e);return g};wwd=function(a){var b=_.ol("HEAD",a);return b&&0!==b.length?b[0]:a.documentElement};twd=function(){if(this&&this.j0c){var a=this.j0c;a&&"SCRIPT"==a.tagName&&uwd(a,!0,this.vY)}};uwd=function(a,b,c){null!=c&&_.ba.clearTimeout(c);a.onload=function(){};a.onerror=function(){};a.onreadystatechange=function(){};b&&window.setTimeout(function(){_.Ll(a)},0)};
vwd=function(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);_.aa.call(this,c);this.code=a};_.Wg(vwd,_.aa);
}catch(e){_._DumpException(e)}
try{
_.l("bgd");
var elh=function(a){var b=new Zkh(a);a?_.C(b,1)?_.C(b,2)?(a=_.C(b,1),b=_.C(b,2),$kh=!0,alh=a,blh=b,clh&&dlh()):rM(14):rM(13):rM(12)},flh=function(){rM(11)},dlh=function(){glh?"complete"===window.document.readyState?hlh():ilh?_.Mk(window,"load",hlh):_.Mk(window.document,"load",hlh):jlh?(0,_.$m)(hlh,jlh):hlh()},hlh=function(){_.Qm(_.$z(_.Aka(alh),{Wwc:!0}),klh,llh)},llh=function(){rM(3)},nlh=function(a){try{a.invoke(mlh)}catch(b){rM(8)}},slh=function(){var a=null;try{a=new window.botguard.bg(blh)}catch(b){rM(6);
return}a.invoke?olh&&(plh&&_.Sd(window,"click",_.Ug(qlh,a),!0),rlh&&_.Sd(window,"unload",function(){return nlh(a)}),plh||rlh||nlh(a)):rM(7)},qlh=function(a,b){if(b=_.Vl(b.target,"A")){var c=!1;if(b.hasAttribute("data-al"))c=!0;else for(var d=b;d;){if("tads"===d.id||"tadsb"===d.id){c=!0;break}d=_.ge(d)}c&&(tlh(b,"href",a)||tlh(b,"data-rw",a))}},tlh=function(a,b,c){var d=a.getAttribute(b);if(!d||!d.includes("aclk?"))return!1;c=c.invoke();c="string"!==typeof c||500<c.length?void 0:c;if(!c)return!0;d=
_.Rta(d+("&bg="+c));a.setAttribute(b,_.mc(d));return!0},klh=function(){ulh&&(window.botguard?window.botguard.bg?vlh?(0,_.$m)(slh,vlh):slh():rM(5):rM(4))},mlh=function(a){wlh&&(a?1875<a.length?rM(10):rM(a):rM(9))},rM=function(a){google.log("srpbgd",String(a))};var Zkh=function(a){_.y.call(this,a)};_.B(Zkh,_.y);var $kh=!1,blh="",alh="",clh=!1,jlh=0,glh=!1,ulh=!1,vlh=0,olh=!1,rlh=!1,plh=!1,wlh=!1,ilh=!1,xlh={};_.Ee("bgd",(xlh.init=function(a){if(!$kh)if(a)if("et"in a&&(vlh=a.et),"ed"in a&&(jlh=a.ed),a.ea&&(glh=!0),a.ei&&(olh=!0),a.eu&&(rlh=!0),a.ac&&(plh=!0),a.ep&&(wlh=!0),a.er&&(ulh=!0),a.el&&(clh=!0),a.as)void 0;else if(a.i)if(a.p){a.wl&&(ilh=!0);var b=String(a.i);a=String(a.p);$kh=!0;alh=b;blh=a;clh&&dlh()}else rM(2);else rM(1);else rM(0)},xlh));
_.n();
}catch(e){_._DumpException(e)}
try{
var EQd;_.FQd=function(a){EQd=EQd||_.Pc("fbarcnt");null!=EQd&&_.t.kb(EQd,a)};EQd=null;
}catch(e){_._DumpException(e)}
try{
_.l("foot");
var GQd={};_.Ee("foot",(GQd.init=function(a){if(void 0!==a.dv&&""!==a.dv)try{_.Uc.set("DV",a.dv,{maxAge:600})}catch(b){_.Hc(b,{Ke:{src:"foot"}})}},GQd));
_.n();
}catch(e){_._DumpException(e)}
try{
var WQl,ZQl,XQl,TQl;WQl=function(){_.Ok(TQl);(0,_.UQl)("kne","enabled");TQl=_.Sd(_.VQl,"keydown",function(a){13!==a.keyCode&&32!==a.keyCode||(0,_.UQl)("kne","selected")})};ZQl=function(){_.Ok(XQl);XQl=_.Mk(_.VQl,"mousedown",function(){_.YQl()},{capture:!0})};_.aRl=function(){_.Ok(XQl);XQl=_.Sd(_.VQl,"keydown",function(a){9===a.keyCode&&_.$Ql()})};_.YQl=function(){_.En.remove(_.VQl,_.bRl);_.cRl&&_.Ok(TQl);_.aRl()};_.$Ql=function(){_.En.add(_.VQl,_.bRl);_.cRl&&WQl();ZQl()};_.cRl=!1;_.VQl=document.documentElement;
}catch(e){_._DumpException(e)}
try{
_.l("kyn");
var Rts=function(a){_.bRl="zAoYTe";_.UQl=a;_.aRl()},Sts={};_.Ee("kyn",(Sts.init=function(){Rts(function(a,b){var c=_.Ld();c.Cc(a,b);c.log()})},Sts));
_.n();
}catch(e){_._DumpException(e)}
try{
var fFd,hFd,jFd,kFd;fFd=function(a){var b;(b=!a.parentElement)||(a.ownerDocument&&a.ownerDocument.defaultView?(b=a.ownerDocument.defaultView.getComputedStyle(a))&&"hidden"===b.visibility?b=!1:(b=a.getBoundingClientRect(),b=0<b.width&&0<b.height):b=!0);return b?a:fFd(a.parentElement)};
hFd=function(a){if(a)for(var b=new gFd,c=_.Wa(Object.keys(a)),d=c.next();!d.done;d=c.next()){var e=d.value;if(d=document.getElementById(e)||document.documentElement.querySelector('img[data-iid="'+e+'"]'))e=a[e],b.ka.ka(d,e)||b.oa.ka(d,e)}};_.iFd=function(){hFd(google.ldi);hFd(google.pim);google.lfj?google.sx(function(){hFd(google.ldilf)}):google.dclc(function(){hFd(google.ldilf)})};jFd=function(a){this.rootMargin=a;this.Sl=null};
kFd=function(a){if(a.Sl)return!0;try{return a.Sl=new IntersectionObserver(function(b,c){b=b.filter(function(e){return e.isIntersecting});b=_.Wa(b);for(var d=b.next();!d.done;d=b.next())d=d.value.target,a.Aa(d),c.unobserve(d)},{rootMargin:a.rootMargin,threshold:[0]}),!0}catch(b){return!1}};var lFd=function(a){jFd.call(this,a);this.oa=new Map;this.wa=new Map};_.B(lFd,jFd);lFd.prototype.ka=function(a,b){return a.hasAttribute("data-atf")?!1:google.lliod?kFd(this)?(mFd(this,a,b),!0):!1:((0,_.ad)(function(){_.Lfd(a,b)}),!0)};lFd.prototype.Aa=function(a){if(a=this.oa.get(a)){a=_.Wa(a);for(var b=a.next();!b.done;b=a.next()){b=b.value;var c=this.wa.get(b);_.Lfd(b,c)}}};var mFd=function(a,b,c){a.wa.set(b,c);c=fFd(b);var d=a.oa.get(c);d?d.push(b):a.oa.set(c,[b]);a.Sl.observe(c)};var nFd=function(a){jFd.call(this,a);this.oa=new Map};_.B(nFd,jFd);nFd.prototype.ka=function(a,b){(google.c.timl||Number(a.getAttribute("data-atf"))&1||google.c.frt&&"1"===a.getAttribute("data-frt")?0:kFd(this))?(this.oa.set(a,b),this.Sl.observe(a)):_.Lfd(a,b);return!0};nFd.prototype.Aa=function(a){var b=this.oa.get(a);_.Lfd(a,b)};var gFd=function(){this.ka=new lFd("0px");this.oa=new nFd("400px")};
}catch(e){_._DumpException(e)}
try{
_.l("lli");
_.iFd();
_.n();
}catch(e){_._DumpException(e)}
try{
_.l("mu");
var wQd=function(a){var b=new Image;b.src=a;_.Mg("google.mu",b)},xQd={};_.Ee("mu",(xQd.init=function(a){var b=a.murl;b&&("complete"===document.readyState?wQd(b):_.Mk(_.Bl(),"load",function(){return wQd(b)},!0,document.documentElement))},xQd));
_.n();
}catch(e){_._DumpException(e)}
try{
_.l("sb_wiz");

_.n();
}catch(e){_._DumpException(e)}
try{
_.l("sf");
var KQd={};_.Ee("sf",(KQd.init=function(){_.ye("sf",{chk:function(a){a.actionElement.ld().checked=!0},lck:function(a){a=a.actionElement.ld();a.form.q.value?(a.checked=!0,(a=a.form.iflsig)&&a.value&&(a.disabled=!1)):_.pc().href="/doodles/"}})},KQd));
_.n();
}catch(e){_._DumpException(e)}
try{
_.lYc=function(a){return _.Dua.apply(null,arguments)/arguments.length};var oYc;_.mYc=/iPhone|iPod|iPad/;_.nYc=function(){return _.pa(navigator.userAgent,"Android")};oYc=/Mac OS X.+Silk\//;_.qw=_.gta||_.mYc.test(navigator.userAgent)||_.nYc()||oYc.test(navigator.userAgent);_.pYc=window.navigator.msPointerEnabled;_.qYc=_.qw?"touchstart":_.pYc?"MSPointerDown":"mousedown";_.rYc=_.qw?"touchmove":_.pYc?"MSPointerMove":"mousemove";_.sYc=_.qw?"touchend":_.pYc?"MSPointerUp":"mouseup";_.tYc=_.pYc?"MSPointerCancel":"touchcancel";_.uYc=function(a){return a.touches||[a]};
}catch(e){_._DumpException(e)}
try{
_.Y_c=function(a){return new RegExp("(?:^| +)"+a+"(?:$| +)")};_.Z_c=function(a,b,c,d){var e=_.Y_c(c),f=d||"",g=_.Y_c(f);if(b!=e.test(a.className)||d&&b==g.test(a.className))d=a.className.replace(e," ").replace(g," "),a.className=d+" "+(b?c:f)};
}catch(e){_._DumpException(e)}
try{
var kUf;_.mI=function(a,b,c,d){this.Pa=!!c;this.Sa=!!d;this.Pa&&(this.Ka=Math.max(800,this.Ka));this.element=a;this.onclick=b;_.qw?a.ontouchstart=(0,_.Tg)(this.nb,this):a.onmousedown=(0,_.Tg)(this.Gb,this);_.pYc&&(a.style.msTouchAction="none");a.onclick=(0,_.Tg)(this.Ra,this);this.Fa=this.Da=null};kUf=function(a){jUf.push(a);window.setTimeout(function(){var b=jUf.indexOf(a);-1!=b&&jUf.splice(b,1)},2500)};
_.mI.prototype.dispose=function(){_.qw?this.element.ontouchstart=null:this.element.onmousedown=null;this.element.onclick=null};
_.mI.prototype.nb=function(a){this.oa&&!this.oa(a)||1<_.uYc(a).length||(this.Sa||a.stopPropagation(),this.Ba=!0,this.Pa||(this.element.ontouchend=(0,_.Tg)(this.Ra,this),document.body.addEventListener("touchend",lUf(this),!1)),document.body.addEventListener("touchmove",mUf(this),!1),document.body.addEventListener("touchcancel",lUf(this),!1),nUf(this),a=a.touches[0],this.ka=new _.Zk(a.clientX,a.clientY),this.Aa?this.Cb=window.setTimeout((0,_.Tg)(this.wa,this,!0),this.Aa):this.wa(!0),this.Pa||kUf(this.ka))};
_.mI.prototype.Gb=function(a){if(!this.oa||this.oa(a))this.Sa||a.stopPropagation(),this.Ba=!0,nUf(this),this.wa(!0)};_.mI.prototype.Ra=function(a){if(this.oa&&!this.oa(a))return oUf(this),!0;if(a){if("touchend"==a.type&&!this.Ba)return!1;a.stopPropagation()}this.wa(!0);window.setTimeout((0,_.Tg)(function(){oUf(this);if(pUf(this))this.onclick(a)},this),0);return!1};
var mUf=function(a){a.Da||(a.Da=function(b){1<_.uYc(b).length?oUf(a):(b=_.uYc(b)[0],b=new _.Zk(b.clientX,b.clientY),a.ka&&12<_.$k(a.ka,b)&&oUf(a))});return a.Da},oUf=function(a){window.clearTimeout(a.Cb);window.clearTimeout(a.Va);a.wa(!1);a.Ba=!1;document.body.removeEventListener&&(document.body.removeEventListener("touchmove",mUf(a),!1),document.body.removeEventListener("touchend",lUf(a),!1),document.body.removeEventListener("touchcancel",lUf(a),!1))},lUf=function(a){a.Fa||(a.Fa=function(){return oUf(a)});
return a.Fa};_.mI.prototype.wa=function(a){this.Ma&&(!a||pUf(this))&&_.Z_c(this.element,a,this.Ma)};var pUf=function(a){if(!document.elementFromPoint||!a.ka||void 0===a.ka.x)return!0;for(var b=document.elementFromPoint(a.ka.x,a.ka.y);b;){if(b==a.element)return!0;b=b.parentNode}return!1},nUf=function(a){a.ob&&(a.Va=window.setTimeout((0,_.Tg)(function(){this.Ba=!1;this.ob()},a),a.Ka))},jUf=[];_.mI.prototype.Aa=100;_.mI.prototype.Ka=500;
}catch(e){_._DumpException(e)}
try{
_.NS=function(a,b,c){var d=c||function(g){_.Hc(g)};c={};var e={},f;for(f in b)e.YCb=b[f],c[f]=function(g){return function(){var h=_.Lc.apply(0,arguments);try{return g.YCb.apply(null,_.Nc(h))}catch(m){d(m)}}}(e),e={YCb:e.YCb};_.xe(a,c)};_.ESk=function(a,b){var c=_.OS(a);return function(){var d=_.Lc.apply(0,arguments);try{b.apply(null,_.Nc(d))}catch(e){c(e)}}};_.ISk=function(){if(!FSk){var a=_.Rd("google.sh.sg");a&&!FSk&&(FSk=new GSk(a),HSk.resolve(FSk))}return FSk||new GSk};_.PS=function(){return _.ISk().lF()};
_.KSk=function(){var a;return!(null==(a=_.JSk())||!_.Ib(a,4))};_.QS=function(){var a;return!(null==(a=_.JSk())||!_.Ib(a,2))};var LSk=function(a){_.y.call(this,a)};_.B(LSk,_.y);var MSk=function(a){_.y.call(this,a)};_.B(MSk,_.y);var NSk=function(a){_.y.call(this,a)};_.B(NSk,_.y);var GSk=function(a){_.y.call(this,a)};_.B(GSk,_.y);_.JSk=function(){var a=_.ISk();return _.q(a,NSk,1)};GSk.prototype.lF=function(){return _.q(this,LSk,2)};_.OSk=function(){var a=_.ISk();return _.q(a,MSk,10)};var HSk=_.$c(),PSk=_.la().ka,FSk;_.bd(_.Zq,PSk);_.OS=function(a){var b={mod:a,prop:"shop"};return function(c,d){if(d){var e=d.getAttribute("href")||null;e&&setTimeout(function(){return(0,_.De)(e,!1)},150)}google.ml(c,!1,b)}};FSk=null;
}catch(e){_._DumpException(e)}
try{
_.l("sonic");
var IVk=function(a){var b=_.PS();if(b=_.Ib(b,185))b=_.PS(),b=_.Ib(b,186);b&&(a.setAttribute("data-sbv2","true"),google.ausb(a));(0,_.De)(a.href)},JVk={};_.Ee("sonic",(JVk.init=function(){_.NS("sonic",{clk:IVk},_.OS("sonic"))},JVk));
_.n();
}catch(e){_._DumpException(e)}
try{
_.tD=function(a){return _.C(a,5)};
}catch(e){_._DumpException(e)}
try{
_.wH=function(a,b){if(!a)return b?null:[];"function"===typeof a&&(a=a());return a instanceof _.y?b?a:a.sQ():a.toArray?a.toArray():a};
}catch(e){_._DumpException(e)}
try{
var NQf,OQf,PQf,QQf,RQf,SQf,TQf,UQf,VQf,WQf,XQf,YQf,hRf;NQf=function(a,b){void 0===a.ssb?Object.defineProperties(a,{ssb:{value:b,configurable:!0,writable:!0,enumerable:!1}}):a.ssb|=b};OQf=function(a){return a.ssb||0};PQf=function(a,b,c,d){Object.defineProperties(a,{TXb:{value:b,configurable:!0,writable:!0,enumerable:!1},sNc:{value:c,configurable:!0,writable:!0,enumerable:!1},qNc:{value:d,configurable:!0,writable:!0,enumerable:!1},rNc:{value:void 0,configurable:!0,writable:!0,enumerable:!1}})};
QQf=function(a){return null!=a.TXb};RQf=function(a){return a.TXb};SQf=function(a,b){a.TXb=b};TQf=function(a){return a.qNc};UQf=function(a,b){a.qNc=b};VQf=function(a){return a.rNc};WQf=function(a,b){a.rNc=b};XQf=function(a){return a.sNc};YQf=function(a,b){return a.sNc=b};_.$Qf=function(a,b){ZQf(a,b);return b};_.aRf=function(a){return null!=a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object};
_.cRf=function(a,b,c,d){b=Math.max(b||500,a.length+1);var e=a.length;e=e&&a[e-1];if(_.aRf(e)){b=a.length;for(var f in e){var g=Number(f);g<b&&(a[g-1]=e[f],delete e[g])}}(0,_.bRf)(a,b,d,c);return a};
_.iRf=function(a,b,c){var d=a;if(Array.isArray(a))c=Array(a.length),(0,_.dRf)(a)?_.eRf(_.cRf(c,(0,_.fRf)(a),(0,_.gRf)(a)),a):hRf(c,a,b),d=c;else if(null!==a&&"object"===typeof a){if(a instanceof Uint8Array||a instanceof _.Ua)return a;if("function"==typeof _.xH&&a instanceof _.xH)return a.oa();d={};for(var e in a)a.hasOwnProperty(e)&&(d[e]=_.iRf(a[e],b,c))}return d};
hRf=function(a,b,c,d){jRf(b)&1&&(0,_.kRf)(a,1);for(var e=0,f=0;f<b.length;++f)if(b.hasOwnProperty(f)){var g=b[f];null!=g&&(e=f+1);a[f]=_.iRf(g,c,d)}c&&(a.length=e)};_.eRf=function(a,b){if(a!==b){a.length=0;var c=(0,_.gRf)(b);null!=c&&(0,_.lRf)(a,c);c=(0,_.fRf)(b);b.length>=c&&(0,_.mRf)(a,c);(c=(0,_.nRf)(b))&&_.$Qf(a,c.Yxc());a.length=b.length;hRf(a,b,!0,b)}};var jRf,ZQf;
if("function"===typeof Symbol&&"symbol"===typeof Symbol()){var qRf=Symbol(void 0),rRf=Symbol(void 0),sRf=Symbol(void 0),tRf=Symbol(void 0),uRf=Symbol(void 0);_.kRf=function(a,b){a[qRf]=jRf(a)|b};jRf=function(a){return a[qRf]||0};_.bRf=function(a,b,c,d){a[rRf]=b;a[uRf]=c;a[sRf]=d;a[tRf]=void 0};_.dRf=function(a){return null!=a[rRf]};_.fRf=function(a){return a[rRf]};_.mRf=function(a,b){a[rRf]=b};_.gRf=function(a){return a[sRf]};_.lRf=function(a,b){a[sRf]=b};_.nRf=function(a){return a[tRf]};ZQf=function(a,
b){a[tRf]=b};_.oRf=function(a){return a[uRf]};_.pRf=function(a,b){return a[uRf]=b}}else _.kRf=NQf,jRf=OQf,_.bRf=PQf,_.dRf=QQf,_.fRf=RQf,_.mRf=SQf,_.gRf=TQf,_.lRf=UQf,_.nRf=VQf,ZQf=WQf,_.oRf=XQf,_.pRf=YQf;_.vRf=Object.freeze([]);
}catch(e){_._DumpException(e)}
try{
var xRf,wRf;xRf=function(a,b){if(a.constructor!==Array&&a.constructor!==Object)throw Error("gi");if(a===b)return!0;if(a.constructor!==b.constructor)return!1;for(var c in a)if(!(c in b&&wRf(a[c],b[c])))return!1;for(var d in b)if(!(d in a))return!1;return!0};wRf=function(a,b){if(a===b||!(!0!==a&&1!==a||!0!==b&&1!==b)||!(!1!==a&&0!==a||!1!==b&&0!==b))return!0;if(a instanceof Object&&b instanceof Object){if(!xRf(a,b))return!1}else return!1;return!0};_.yH=function(){return _.yRf()?"rtl":"ltr"};_.zRf=function(){};_.zRf.prototype.initialize=function(a){this.ka=a||{}};_.zH=function(a,b,c){a=a.ka[b];return null!=a?a:c};_.zRf.prototype.equals=function(a){a=a&&a;return!!a&&xRf(this.ka,a.ka)};_.zRf.prototype.clone=function(){var a=this.constructor,b={},c=this.ka;if(b!==c){for(var d in b)b.hasOwnProperty(d)&&delete b[d];if(c)for(var e in c)c.hasOwnProperty(e)&&(b[e]=_.iRf(c[e]))}return new a(b)};var ARf=function(a){this.initialize(a)},CRf;_.Wg(ARf,_.zRf);ARf.prototype.getLanguage=function(){return _.zH(this,"language","")};_.yRf=function(){var a=_.AH();return!!_.zH(a,"is_rtl")};CRf=function(a){BRf.ka.css3_prefix=a};var BRf;_.AH=function(){BRf||(BRf=new ARf,_.oba()?CRf("-webkit-"):_.wh.qva()?CRf("-moz-"):_.wh.Sna()?CRf("-ms-"):_.wh.Tsb()&&CRf("-o-"),BRf.ka.is_rtl=!1,BRf.ka.language="en-GB");return BRf};BRf=null;
}catch(e){_._DumpException(e)}
try{
var IRf,KRf,MRf,PRf,QRf,TRf,VRf,URf,LRf,DRf,GRf,ERf,FRf,HRf,$Rf,JRf,cSf;_.BH=function(a,b){if(DRf.test(b))return b;b=0<=b.indexOf("left")?b.replace(ERf,"right"):b.replace(FRf,"left");_.Ca(GRf,a)&&(a=b.split(HRf),4<=a.length&&(b=[a[0],a[3],a[2],a[1]].join(" ")));return b};IRf=function(a,b){a[b]||(a[b]=[]);return a[b]};KRf=function(a,b){for(var c=_.Wa(_.OYa.keys()),d=c.next();!d.done;d=c.next())if(d=d.value,_.OYa.get(d)===b)return d;return a+";;"+JRf++};
MRf=function(a,b){var c=KRf(a,b);_.OYa.set(c,b);_.PYa.has(a)||(LRf(a,function(){return""}),_.PYa.add(a));return c};_.CH=function(a){a=_.nc(a).toString();return"about:invalid#zClosurez"===a?"about:invalid#zjslayoutz":a};_.DH=function(a){if(NRf.test(a))return a;a=_.nc(a).toString();return"about:invalid#zClosurez"===a?"about:invalid#zjslayoutz":a};
_.EH=function(a){if(null==a)return null;if(!ORf.test(a)||0!=PRf(a,0))return"zjslayoutzinvalid";for(var b=RegExp("([-_a-zA-Z0-9]+)\\(","g"),c;null!==(c=b.exec(a));)if(null===QRf(c[1],!1))return"zjslayoutzinvalid";return a};PRf=function(a,b){if(0>b)return-1;for(var c=0;c<a.length;c++){var d=a.charAt(c);if("("==d)b++;else if(")"==d)if(0<b)b--;else return-1}return b};
_.FH=function(a){if(null==a)return null;for(var b=RegExp("([-_a-zA-Z0-9]+)\\(","g"),c=RegExp("[ \t]*((?:\"(?:[^\\x00\"\\\\\\n\\r\\f\\u0085\\u000b\\u2028\\u2029]*)\"|'(?:[^\\x00'\\\\\\n\\r\\f\\u0085\\u000b\\u2028\\u2029]*)')|(?:[?&/:=]|[+\\-.,!#%_a-zA-Z0-9\t])*)[ \t]*","g"),d=!0,e=0,f="";d;){b.lastIndex=0;var g=b.exec(a);d=null!==g;var h=a,m=void 0;if(d){if(void 0===g[1])return"zjslayoutzinvalid";m=QRf(g[1],!0);if(null===m)return"zjslayoutzinvalid";h=a.substring(0,b.lastIndex);a=a.substring(b.lastIndex)}e=
PRf(h,e);if(0>e||!ORf.test(h))return"zjslayoutzinvalid";f+=h;if(d&&"url"==m){c.lastIndex=0;g=c.exec(a);if(null===g||0!=g.index)return"zjslayoutzinvalid";m=g[1];if(void 0===m)return"zjslayoutzinvalid";g=0==m.length?0:c.lastIndex;if(")"!=a.charAt(g))return"zjslayoutzinvalid";h="";1<m.length&&(_.ff(m,'"')&&_.vqa(m,'"')?(m=m.substring(1,m.length-1),h='"'):_.ff(m,"'")&&_.vqa(m,"'")&&(m=m.substring(1,m.length-1),h="'"));m=_.DH(m);if("about:invalid#zjslayoutz"==m)return"zjslayoutzinvalid";f+=h+m+h;a=a.substring(g)}}return 0!=
e?"zjslayoutzinvalid":f};QRf=function(a,b){var c=a.toLowerCase();a=RRf.exec(a);if(null!==a){if(void 0===a[1])return null;c=a[1]}return b&&"url"==c||c in SRf?c:null};_.GH=function(a){return null==a?null:a instanceof _.y?a.Il:a.toArray?a.toArray():a};TRf=function(a){return null!=a&&"object"===typeof a&&a.constructor===Object};
VRf=function(a,b){a=URf(a);if("number"==typeof b&&0>b){var c=a.length;if(null==c)return a[-b];b=-b-1;b<c&&(b!==c-1||!TRf(a[c-1]))?b=a[b]:(a=a[a.length-1],b=TRf(a)?a[b+1]||null:null);return b}return a[b]};URf=function(a){return null!=a&&"object"==typeof a&&a instanceof _.y?a.Il:a};_.S=function(a,b){a=_.GH(a);for(var c=1;c<arguments.length;++c){if(null==a||null==arguments[c])return!1;a=VRf(a,arguments[c])}return null!=a};_.WRf=function(a){return a?"rtl":"ltr"};LRf=function(a,b){_.dp[a]=b};DRf=/['"\(]/;
GRf=["border-color","border-style","border-width","margin","padding"];ERf=/left/g;FRf=/right/g;HRf=/\s+/;_.XRf=function(a,b){return IRf(a.ka,b)};_.YRf=function(a,b){var c={};_.XRf(a,b).push(c);return c};_.ZRf=function(a,b){return a.ka[b]?a.ka[b].length:0};$Rf=function(a){this.initialize(a)};_.Wg($Rf,_.zRf);$Rf.prototype.getName=function(){return _.zH(this,"name","")};$Rf.prototype.Wc=function(a){this.ka.name=a};var aSf=function(a){this.initialize(a)};_.Wg(aSf,_.zRf);
aSf.prototype.addRule=function(){return new $Rf(_.YRf(this,"rule"))};JRf=1;_.bSf=function(){window.W_jd&&window.W_jd.tq7Pxb&&(_.Wfd(new _.Sfd(window.W_jd.tq7Pxb)),delete window.W_jd.tq7Pxb)};cSf=function(a){_.bSf();return _.Tfd[a]?_.Tfd[a]:new _.Mfd};_.T=function(a){return!!_.Vi(cSf(a),2,_.Nfd)};_.HH=function(a){a=cSf(a);return null!=_.aj(a,5,_.Nfd)?_.Yi(a,5,_.Nfd)||0:null!=_.Tra(a,_.Uh(a,_.Nfd,4))?_.Fi(a,_.Uh(a,_.Nfd,4))||0:0};_.IH=function(a){return cSf(a).getStringValue()||""};_.JH=function(){return _.AH().ka};var NRf,SRf,ORf,RRf;NRf=RegExp("^data:image/(?:bmp|gif|jpeg|jpg|png|tiff|webp|x-icon);base64,[-+/_a-z0-9]+(?:=|%3d)*$","i");_.dSf=RegExp("^(?:[0-9]+)([ ]*;[ ]*url=)?(.*)$");
SRf={blur:!0,brightness:!0,calc:!0,circle:!0,contrast:!0,counter:!0,counters:!0,"cubic-bezier":!0,"drop-shadow":!0,ellipse:!0,grayscale:!0,hsl:!0,hsla:!0,"hue-rotate":!0,inset:!0,invert:!0,opacity:!0,"linear-gradient":!0,matrix:!0,matrix3d:!0,minmax:!0,polygon:!0,"radial-gradient":!0,rgb:!0,rgba:!0,rect:!0,repeat:!0,rotate:!0,rotate3d:!0,rotatex:!0,rotatey:!0,rotatez:!0,saturate:!0,sepia:!0,scale:!0,scale3d:!0,scalex:!0,scaley:!0,scalez:!0,steps:!0,skew:!0,skewx:!0,skewy:!0,translate:!0,translate3d:!0,
translatex:!0,translatey:!0,translatez:!0,"var":!0};ORf=RegExp("^(?:[*/]?(?:(?:[+\\-.,!#%_a-zA-Z0-9\t]| )|\\)|[a-zA-Z0-9]\\(|$))*$");_.eSf=RegExp("^(?:[*/]?(?:(?:\"(?:[^\\x00\"\\\\\\n\\r\\f\\u0085\\u000b\\u2028\\u2029]|\\\\(?:[\\x21-\\x2f\\x3a-\\x40\\x47-\\x60\\x67-\\x7e]|[0-9a-fA-F]{1,6}[ \t]?))*\"|'(?:[^\\x00'\\\\\\n\\r\\f\\u0085\\u000b\\u2028\\u2029]|\\\\(?:[\\x21-\\x2f\\x3a-\\x40\\x47-\\x60\\x67-\\x7e]|[0-9a-fA-F]{1,6}[ \t]?))*')|(?:[+\\-.,!#%_a-zA-Z0-9\t]| )|$))*$");RRf=RegExp("^-(?:moz|ms|o|webkit|css3)-(.*)$");_.fSf=function(a,b){this.oa="";this.ka=b||{};if("string"===typeof a)this.oa=a;else{b=a.ka;this.oa=a.getKey();for(var c in b)null==this.ka[c]&&(this.ka[c]=b[c])}};_.fSf.prototype.getKey=function(){return this.oa};_.gSf=_.vfa({"for":"htmlFor","class":"className"});var hSf,iSf,jSf,lSf,mSf,nSf,oSf,kSf,pSf;hSf=RegExp("^</?(b|u|i|em|br|sub|sup|wbr|span)( dir=(rtl|ltr|'ltr'|'rtl'|\"ltr\"|\"rtl\"))?>");iSf=RegExp("^&([a-zA-Z]+|#[0-9]+|#x[0-9a-fA-F]+);");jSf={"<":"&lt;",">":"&gt;","&":"&amp;",'"':"&quot;"};_.V=function(a){if(null==a)return"";if(!kSf.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(lSf,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(mSf,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(nSf,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(oSf,"&quot;"));return a};
_.KH=function(a){if(null==a)return"";-1!=a.indexOf('"')&&(a=a.replace(oSf,"&quot;"));return a};lSf=/&/g;mSf=/</g;nSf=/>/g;oSf=/"/g;kSf=/[&<>"]/;pSf=null;_.qSf=function(a){for(var b="",c,d=0;c=a[d];++d)switch(c){case "<":case "&":var e=("<"==c?hSf:iSf).exec(a.substr(d));if(e&&e[0]){b+=a.substr(d,e[0].length);d+=e[0].length-1;continue}case ">":case '"':b+=jSf[c];break;default:b+=c}null==pSf&&(pSf=document.createElement("div"));_.hd(pSf,_.Ie(b));return pSf.innerHTML};_.rSf=function(a){var b=a[1]=_.hm(a[0]);if(b[6]){for(var c=b[6].split("&"),d={},e=0,f=c.length;e<f;++e){var g=c[e].split("=");if(2==g.length){var h=g[1].replace(/,/gi,"%2C").replace(/[+]/g,"%20").replace(/:/g,"%3A");try{d[decodeURIComponent(g[0])]=decodeURIComponent(h)}catch(m){}}}b[6]=d}a[0]=null};
_.sSf=function(a){if(a[6]){var b=a[6];var c=[],d;for(d in b){var e=b[d];null!=e&&c.push(encodeURIComponent(d)+"="+encodeURIComponent(e).replace(/%3A/gi,":").replace(/%20/g,"+").replace(/%2C/gi,",").replace(/%7C/gi,"|"))}b=c.join("&");a[6]=b}"http"==a[1]&&"80"==a[4]&&(a[4]=null);"https"==a[1]&&"443"==a[4]&&(a[4]=null);b=a[3];/:[0-9]+$/.test(b)&&(c=b.lastIndexOf(":"),a[3]=b.substr(0,c),a[4]=b.substr(c+1));b=a[5];a[3]&&b&&!b.startsWith("/")&&(a[5]="/"+b);return _.gja(a[1],a[2],a[3],a[4],a[5],a[6],a[7])};
_.tSf=function(a,b){var c=[];b&&(b=[b],_.rSf(b),c=b[1]);a.scheme?c[1]=a.scheme:null===a.scheme&&(c[1]=void 0);a.domain&&(c[3]=a.domain);a.port?c[4]=a.port:null===a.port&&(c[4]=void 0);a.path&&(c[5]=a.path);a.fragment?c[7]=a.fragment:null===a.fragment&&(c[7]=void 0);if(a.K4){var d=c[6]||{};Object.entries(a.K4).forEach(function(e){var f=_.Wa(e);e=f.next().value;f=f.next().value;void 0!==f?d[e]=f:null===f&&delete d[e]});c[6]=d}return _.sSf(c)};_.LH=function(a){return a||"#"};
_.MH=function(a){return a||"/images/cleardot.gif"};var uSf;uSf=null;_.NH=function(a,b){return _.BH(a,b)};_.vSf=function(a,b,c){switch(_.YVa(a,b)){case 1:return"ltr";case -1:return"rtl";default:return c}};_.OH=function(a,b){return null==a?null:new _.fSf(a,b)};_.PH=function(a,b){return Array.isArray(b)?new a(b):b};_.W=function(a,b,c){a=_.GH(a);for(var d=2;d<arguments.length;++d){if(null==a||null==arguments[d])return b;a=VRf(a,arguments[d])}return null==a?b:URf(a)};
_.QH=function(a){a=_.GH(a);for(var b=1;b<arguments.length;++b){if(null==a||null==arguments[b])return 0;a=VRf(a,arguments[b])}return null==a?0:a?a.length:0};_.wSf=function(a){var b=1;0>b&&(b=0);return parseFloat(a).toFixed(b)};_.RH=function(a){uSf||(uSf=new _.my(1));return uSf.format(a)};_.SH=function(a,b){return a?a.join(void 0===b?",":b):""};
_.xSf=function(a){if(null==a)a=[];else{var b=null!=a.length,c=a._jslArrayCache;c||(c=[],a._jslArrayCache=c);var d=b?a.length:a.size();c.length=d;for(var e=a.getAtIndex?"getAtIndex":"get",f=0;f<d;f++){var g=b?a[f]:a[e](f);c[f]=g}a=c}return a};_.ySf=function(a,b){for(var c=0;c<b.length;++c)if(_.S(a,-b[c]))return b[c];return 0};
_.TH=function(a,b){var c=_.AH();c=new aSf(c.ka.css3_prefix_rules);for(var d=[],e=0;e<_.ZRf(c,"rule");e++){var f=d,g=f.push;var h=e;h=_.XRf(c,"rule")[h];g.call(f,new $Rf(h))}c=_.Wa(d.slice().values());for(d=c.next();!d.done;d=c.next())if(d=d.value,d.getName()===a&&0===_.zH(d,"role",0)||_.zH(d,"role",0)===b)return _.zH(d,"prefixed_name","");_.bSf();if(c=_.Ufd)for(c=_.Wa(_.mi(c,_.Pfd,1)),d=c.next();!d.done;d=c.next())if(d=d.value,_.Jb(d,1)===a&&0===_.Oi(d,3,0)||_.Oi(d,3,0)===b)return _.C(d,2);b=_.AH();
return _.zH(b,"css3_prefix","")+a};_.UH=function(a,b,c){c=~~(c||0);0==c&&(c=1);var d=[];if(0<c)for(a=~~a;a<b;a+=c)d.push(a);else for(a=~~a;a>b;a+=c)d.push(a);return d};_.VH=function(a){return"number"===typeof a?a:a.toNumber()};_.WH=function(a,b){return MRf(a,b||[])};_.XH=function(a){for(var b=[],c=0;c<a.length;c++)b.push({item:a[c],index:c,length:a.length});return b};
_.X=function(a){var b=a.match(/\bhref="/g);if(!b||1>=b.length)return a;var c=new _.Ao;a=a.replace(/\bhref="(.*?)"/g,function(d,e){d=_.No(e);c.Aa||_.Do(c,d.Aa);c.wa||_.Fo(c,d.wa);c.oa||c.setPath(d.oa);c.Ba||_.Io(c,d.Ba);e=_.Wa(d.ka.yy());for(var f=e.next();!f.done;f=e.next())f=f.value,_.dQa(c.ka,f)||_.XPa(c.ka,f,d.ka.Bt(f));return""});a=a.replace(/\s\s+/g," ").replace(/\s+$/g,"");return a+' href="'+c.toString()+'"'};
_.Y=function(a){return""===a?"":' class="'+(" "===a.charAt(a.length-1)?a.slice(0,-1):a)+'"'};_.Z=function(a){return""!==a?' style="'+a+'"':""};_.YH=function(a,b){return b instanceof _.y?b:new a(b)};
}catch(e){_._DumpException(e)}
try{
_.nTf=function(a){if(!a)return _.yH();for(a=a.parentNode;_.je(a);a=a.parentNode){var b=a.getAttribute("dir");if(b&&(b=b.toLowerCase(),"ltr"==b||"rtl"==b))return b}return _.yH()};_.oTf=function(){this.ka={}};_.oTf.prototype.add=function(a,b){this.ka[a]=b;return!1};_.pTf=function(a,b){this.ka=a=void 0===a?document:a;this.wa=null;this.Ba={};this.oa=[];this.Da=(void 0===b?0:b)&&this.ka?_.yh(this.ka.getElementsByTagName("style"),function(c){return c.innerHTML}).join():"";this.Aa=!1};_.pTf.prototype.document=function(){return this.ka};var qTf=function(a){var b=a.ka.createElement("STYLE");a.ka.head?a.ka.head.appendChild(b):a.ka.body.appendChild(b);return b};_.hI=function(a,b,c){a=void 0===a?document:a;b=void 0===b?new _.oTf:b;c=void 0===c?new _.pTf(a):c;this.ob=a;this.Va=c;this.Ka=b;a=function(){};a.prototype.ka=function(d){return b.ka[d]};this.Aa=new a;this.Ra={};this.nb=[_.yRf()]};_.k=_.hI.prototype;_.k.La=function(a){var b=this.Va;a in b.Ba||(b.Ba[a]=!0,-1==b.Da.indexOf(a)&&b.oa.push(a))};_.k.document=function(){return this.ob};_.k.vj=function(){this.Va.Aa=!0};
_.k.Ae=function(){var a=this.Va;if(a.ka&&0!=a.oa.length){var b=a.oa.join("");if(a.Aa)a=b;else{if(_.Bh){a.wa||(a.wa=qTf(a));var c=a.wa}else c=qTf(a);c.styleSheet&&!c.sheet?c.styleSheet.cssText+=b:c.textContent+=b;a.oa.length=0;a=""}}else a="";return a};
_.k.Na=function(a,b,c,d,e,f,g,h,m,r,u,w){e=void 0===e?null:e;f=void 0===f?null:f;g=void 0===g?"":g;h=void 0===h?null:h;m=void 0===m?"":m;r=void 0===r?null:r;u=void 0===u?"":u;w=void 0===w?null:w;this.Ra[a]={args:_.rTf(b),A6a:c,NJe:d,L_c:e,pPe:f,O_c:g,I_c:h,P_c:m,J_c:r,Q_c:u,K_c:w,light:!0}};_.k.kq=function(a,b,c,d,e,f){a=this.Ra[a];a.L_c=b;a.O_c="";a.I_c=c;a.P_c=d;a.J_c=e;a.Q_c="";a.K_c=f};_.rTf=function(a){if(Array.isArray(a))return a;var b=[],c;for(c in a)b[a[c]]=c;return b};
_.hI.prototype.ka=function(a){return a in this.Ra};_.hI.prototype.Ma=function(a){return this.Ra[a]||null};_.sTf=function(a,b){a.Fa=b};_.hI.prototype.isRtl=function(){return _.xa(this.nb)};_.hI.prototype.Da=function(a){this.nb[0]="rtl"==_.nTf(a)};_.hI.prototype.Ba=function(){this.Fa&&this.Fa.Vv()};
}catch(e){_._DumpException(e)}
try{
_.l("spch");
var i1r=function(){if(g1r){var a=.5+.55*Math.random(),b=Math.round(170+10*Math.random());h1r.style.setProperty("-webkit-transition","-webkit-transform "+b/1E3+"s ease-in-out");h1r.style.setProperty("-webkit-transform","scale("+a+")");window.setTimeout(i1r,b)}else h1r.style.removeProperty("opacity"),h1r.style.removeProperty("-webkit-transition"),h1r.style.removeProperty("-webkit-transform")},n1r=function(){j1r=k1r;l1r=_.nl("spchf");TV=_.nl("spchi");m1r();return!(!l1r||!TV)},r1r=function(a,b,c){window.clearTimeout(o1r);
window.clearTimeout(p1r);c?(_.hd(TV,_.mz(a)),_.hd(l1r,_.mz(b)),a=TV.firstElementChild,a.id="spchta",_.Sl(a,!0),_.En.set(a,"spchta")):(TV.textContent=a,l1r.textContent=b);a=TV;b=l1r;0===q1r&&(q1r=j1r?28:27);c=1.2*q1r+1;var d=2.4*q1r+1,e=1.2*q1r*3+1,f="spcht";TV.scrollHeight>4.8*q1r+1?f+=" spch-5l":TV.scrollHeight>e?f+=" spch-4l":TV.scrollHeight>d?f+=" spch-3l":TV.scrollHeight>c&&(f+=" spch-2l");a.className=b.className=f},t1r=function(){TV.textContent="";l1r.textContent="";o1r=window.setTimeout(function(){""===
TV.textContent&&r1r(s1r.waiting,"")},300)},m1r=function(){window.clearTimeout(p1r);window.clearTimeout(o1r);q1r=0;_.En.set(TV,"spcht");_.En.set(l1r,"spcht")},u1r=function(){function a(){var d=s1r.tU,e=0<b&&TV.textContent!==d.substring(0,b),f=0===b&&TV.textContent!==s1r.ready;b===d.length||e||f||(c+=d.substring(b,b+1),r1r(c,""),++b,p1r=window.setTimeout(a,30))}var b=0,c="";p1r=window.setTimeout(a,2E3)},y1r=function(a){var b=v1r;w1r&&(_.En.set(x1r,"spchc s2ra"),r1r(a,b))},A1r=function(a){_.En.set(x1r,
"spchc s2er");switch(a){case "8":r1r(s1r.MTc,"",!0);break;case "0":r1r(s1r.NTc,"",!0);break;case "2":r1r(s1r.Kuc,"",!0);break;case "3":r1r(s1r.lTa,"");break;case "4":case "5":r1r(s1r.WWc,"",!0);break;case "7":r1r(s1r.VPc,"")}k1r||(g1r=!1);"8"===a&&(z1r=!0)},D1r=function(){B1r=_.Pc("spch-dlg");C1r=_.Pc("spch");x1r=_.Pc("spchc")},F1r=function(a){w1r&&k1r&&"vso"!==a&&E1r()},I1r=function(a){if(w1r){a=(null==a?void 0:a.target).id;var b="";"spchx"===a?G1r="0":"spch"===a?G1r="2":"spchb"===a?G1r="1":"spchta"===
a?G1r="5":b=a;H1r(G1r,b,"1"===G1r&&!z1r,("1"===G1r||"5"===G1r)&&z1r)}},M1r=function(){UV=-1;_.pS(_.qS.yqc);_.Nk(window,"keydown",J1r);_.oS(_.qS.dKb,K1r);_.oS(_.qS.wqc,K1r);_.oS(_.qS.vqc,L1r)},U1r=function(){VV=new window.webkitSpeechRecognition;VV.continuous=!1;VV.interimResults=!0;VV.lang=N1r;VV.maxAlternatives=4;VV.onerror=O1r;VV.onnomatch=P1r;VV.onend=Q1r;VV.onresult=R1r;VV.onaudiostart=S1r;VV.onspeechstart=T1r},X1r=function(){7!==UV&&_.pS(_.qS.tqc);10===UV&&(UV=11,VV.abort());window.removeEventListener("mouseup",
I1r,!1);k1r?_.fe("fpstate")&&_.ee():k1r||(g1r=!1);(V1r||k1r)&&B1r.close();_.En.set(C1r,"spch");_.En.set(x1r,"spchc");C1r.removeAttribute("style");_.t.kb(C1r,!1);z1r=w1r=!1;m1r();W1r()},Z1r=function(a,b,c){Y1r(a,b,c);UV=10;X1r()},W1r=function(){window.clearTimeout($1r);window.clearTimeout(a2r);window.clearTimeout(b2r);_.pS(_.qS.Aqc);_.Nk(_.Oc(),"visibilitychange",c2r,!1);v1r=d2r=e2r="";UV=0;VV.abort()},S1r=function(){f2r(8E3);window.clearTimeout(b2r);UV=4;w1r&&(_.En.set(x1r,"spchc s2ml"),window.clearTimeout(o1r),
r1r(s1r.ready,""),u1r())},T1r=function(){f2r(8E3);UV=5;w1r&&(_.En.set(x1r,"spchc s2ra"),V1r||k1r||C1r.classList.add("mVRQbc"),k1r||g1r||(g1r=!0,i1r()),window.clearTimeout(p1r))},R1r=function(a){f2r(8E3);switch(UV){case 6:case 5:break;case 4:T1r();break;case 3:T1r();S1r();break;default:return}var b=a.results,c=b.length;if(0!==c){UV=6;v1r=d2r="";var d=a.resultIndex;if(a=b[d].isFinal)v1r=b[d][0].transcript,y1r(v1r);else{for(d=0;d<c;d++){var e=b[d][0].transcript;d2r+=e;.5<b[d][0].confidence&&(v1r+=e)}y1r(d2r)}6===
UV&&(a||120<d2r.length?(e2r=v1r,g2r(18)):(e2r=d2r,_.pS(_.qS.zqc,[e2r])))}},O1r=function(a){f2r(8E3);window.clearTimeout(b2r);var b=h2r(a.error);if("1"!==b){var c="";"9"===b&&(c=a.error);Y1r(2,b,c);UV=8;A1r(b);window.clearTimeout($1r);i2r(j2r)}},P1r=function(){Y1r(4);UV=8;A1r("8");window.clearTimeout($1r);i2r(8E3)},Q1r=function(){window.clearTimeout($1r);window.clearTimeout(b2r);var a="9";switch(UV){case 3:UV=9;a="2";break;case 4:UV=9;a="0";break;case 5:case 6:UV=9;a="8";break;case 8:break;default:return}switch(UV){case 9:A1r(a);
i2r(8E3);Y1r(3,a);UV=11;break;case 8:UV=11;break;default:UV=11,X1r()}},J1r=function(a){if(k2r()&&-1!==UV){var b=a.ctrlKey||_.Hh&&a.metaKey;0===UV&&190===a.keyCode&&a.shiftKey&&b&&K1r(l2r)}else if(a.stopPropagation(),27===a.keyCode)Z1r(0,"0");else if(b=a.keyCode,13===b||32===b){if(b=null!=a.target)b=a.target.id,b="spchta"===b||"spchx"===b;b?I1r(a.Af):e2r&&g2r(3)}},m2r=function(){if(""!==v1r)e2r=v1r,g2r(19);else switch(UV){case 3:case 4:case 5:case 6:case 8:Z1r(0,"3")}},n2r=function(){f2r(15E3);Y1r(0,
"6");w1r&&_.En.set(x1r,"spchc s2wfp")},c2r=function(){k2r()||_.Oc().XJ()&&Z1r(0,"4")},L1r=function(){k2r()||Z1r(0,"7")},g2r=function(a){UV=7;window.clearTimeout($1r);var b=e2r;X1r();_.pS(_.qS.uqc,[b,a])},h2r=function(a){switch(a){case "no-speech":return j2r=8E3,"0";case "aborted":return j2r=3E3,"1";case "audio-capture":return j2r=8E3,"2";case "network":return j2r=3E3,"3";case "not-allowed":return j2r=8E3,"4";case "service-not-allowed":return j2r=8E3,"5";case "bad-grammar":return j2r=3E3,"6";case "language-not-supported":return j2r=
3E3,"7";default:return j2r=3E3,"9"}},Y1r=function(a,b,c){var d="";b&&(d+="&reason="+b);c&&(d+="&data="+c);google.log("spch-recog",a+d)},f2r=function(a){window.clearTimeout($1r);$1r=window.setTimeout(m2r,a)},i2r=function(a){window.clearTimeout(a2r);a2r=window.setTimeout(X1r,a)},k2r=function(){switch(UV){case 0:case -1:case 1:return!0}return!1},K1r=function(a){if(l2r=void 0===a?!1:a)Y1r(0,"5","S3 isn't ready to use.");else if((a=_.Pc("spch"))&&_.Nm(a,"clicked"),-1===UV)Y1r(5);else if(0!==UV)Z1r(0,"5");
else if(UV=2,2===UV){w1r||(D1r(),n1r(),t1r(),w1r||(_.t.kb(C1r,!0),k1r&&_.ce("fpstate","vso"),(k1r||V1r)&&B1r.showModal(),_.En.set(C1r,"spch"),_.En.set(C1r,"spch s2fp"),w1r=!0),window.addEventListener("mouseup",I1r,!1));f2r(8E3);window.clearTimeout(b2r);b2r=window.setTimeout(n2r,1500);_.pS(_.qS.PVd);_.Sd(_.Oc(),"visibilitychange",c2r,!1);VV&&VV.onerror&&VV.onnomatch&&VV.onend&&VV.onresult&&VV.onaudiostart&&VV.onspeechstart||U1r();try{VV.start(),UV=3}catch(b){UV=2;U1r();try{VV.start(),UV=3}catch(c){UV=
10,Y1r(0,"1"),X1r()}}}},o2r=function(a,b,c,d){e2r&&c?g2r(17):11===UV&&d?(Y1r(6,a,b),W1r(),K1r(l2r)):Z1r(1,a,b)},p2r=function(){Z1r(8,"8")},s1r={Kuc:"",VPc:"",tU:"",lTa:"",MTc:"",NTc:"",WWc:"",ready:"",waiting:""};var q2r,h1r,g1r=!1;var l1r,TV,q1r,o1r,p1r,j1r;var G1r="4",k1r=!1,V1r=!1,B1r,C1r,x1r,z1r=!1,w1r=!1,H1r,E1r;var s2r;_.r2r=new Set;s2r=function(a){return _.r2r.has(a)};var v2r=function(a){t2r(a);return u2r(a)},w2r=function(a){t2r(a);var b="<style"+_.Y("")+_.Z("")+_.X("")+">";a=u2r(a);return _.v(b+(a+"</style>"))},u2r=function(a){var b=_.wH(_.z().Ub,!1);b=_.W(b,"",-250);a.La(".permission-bar{margin-top:-100px;opacity:0;pointer-events:none;position:absolute;width:500px;transition:opacity 0.218s ease-in,margin-top .4s ease-in}");a.La(".s2wfp .permission-bar{margin-top:-300px;opacity:1;transition:opacity .5s ease-out 0.218s,margin-top 0.218s ease-out 0.218s}");a.La(".permission-bar-gradient{box-shadow:0 1px 0px "+
(b+";height:80px;left:0;margin:0;opacity:0;pointer-events:none;position:fixed;right:0;top:-80px;transition:opacity 0.218s,box-shadow 0.218s}"));a.La(".s2wfp .permission-bar-gradient{box-shadow:0 1px 80px "+b+";opacity:1;pointer-events:none;"+_.TH("animation",1)+":allow-alert .75s 0 infinite;"+_.TH("animation-direction",1)+":alternate;"+_.TH("animation-timing-function",1)+":ease-out;transition:opacity 0.218s,box-shadow 0.218s}");a.La("@-webkit-keyframes allow-alert {from{opacity:1}to{opacity:.35}}");
return""},t2r=function(a){a.ka(x2r)||a.Na(x2r,{},v2r,w2r)},x2r="t-_wSOtLKeKkA";var y2r=function(){return""},z2r=function(){return""},A2r=function(){return""},B2r=function(){return!0},C2r=function(){return!1},F2r=function(a){D2r(a);return E2r(a)},G2r=function(a){D2r(a);var b="<div"+_.Y("permission-bar ")+_.Z("")+_.X("")+">";a=E2r(a);return _.v(b+(a+"</div>"))},E2r=function(a){return u2r(a)+"<div"+_.Y("permission-bar-gradient ")+_.Z("")+_.X("")+"></div>"},D2r=function(a){a.ka(H2r)||(a.Na(H2r,{},F2r,G2r,B2r,C2r,"",y2r,"permission-bar ",z2r,"",A2r),t2r(a))},H2r="t-y4DJ78xmMWs";var I2r=function(){return""},J2r=function(){return""},K2r=function(){return""},L2r=function(){return!0},M2r=function(){return!1},P2r=function(a){N2r(a);return O2r()},Q2r=function(a){N2r(a);return _.v(O2r())},O2r=function(){return"close"},N2r=function(a){a.ka(R2r)||a.Na(R2r,{},P2r,Q2r,L2r,M2r,"",I2r,"",J2r,"",K2r)},R2r="t-2UBRBUtV38g";var U2r=function(a){S2r(a);return T2r(a)},V2r=function(a){S2r(a);a=T2r(a);return _.v(a)},T2r=function(a){var b=_.wH(_.z().Wa,!1),c=_.wH(_.z().Ub,!1);a.La(".spch-dlg{background:"+_.W(b,"",-36)+";border:none}");a.La(".spch{background:"+(_.W(b,"",-10)+";height:100%;left:0;opacity:0;overflow:hidden;position:fixed;text-align:left;top:0;visibility:hidden;width:100%;z-index:10000;transition:visibility 0s linear 0.218s,background-color 0.218s;"+(s2r("Ftxme")||s2r("POUY7e")?"":"background:"+_.W(c,"",-196))+
"}"));a.La(".s2fp.spch{opacity:1;transition-delay:0s;"+(s2r("POUY7e")&&s2r("Ftxme")?"visibility:inherit;":"")+(s2r("Ftxme")?"":"visibility:visible;")+(s2r("POUY7e")||s2r("Ftxme")?"":"background:"+_.W(c,"",-196))+"}");a.La(".close-button{background:none;border:none;color:"+(_.W(b,"",-5)+";cursor:pointer;font-size:26px;right:0;line-height:15px;opacity:.6;margin:-1px -1px 0 0;padding:0 0 2px 0;height:48px;width:48px;position:absolute;top:0;z-index:10}"));a.La(".close-button:hover{opacity:.8}");a.La(".close-button:active{opacity:1}");
a.La(".spchc{display:block;height:42px;pointer-events:none;"+(s2r("POUY7e")?"margin:auto;position:relative;top:0;":"")+(s2r("Ftxme")&&s2r("POUY7e")?"margin-top:312px;max-width:400px;padding:0 100px;":"")+(!s2r("Ftxme")&&s2r("POUY7e")?"margin-top:312px;max-width:572px;min-width:534px;padding:0 223px":"")+"}");a.La(".inner-container{height:100%;opacity:.1;pointer-events:none;width:100%;transition:opacity .318s ease-in}");a.La(".s2ml .inner-container,.s2ra .inner-container,.s2er .inner-container{opacity:1;transition:opacity 0s}");
return""},S2r=function(a){a.ka(W2r)||a.Na(W2r,{},U2r,V2r)},W2r="t-I44BHHE4hj0";_.X2r=new Set;var $2r=function(a){Y2r(a);return Z2r(a)},a3r=function(a){Y2r(a);var b="<style"+_.Y("")+_.Z("")+_.X("")+">";a=Z2r(a);return _.v(b+(a+"</style>"))},Z2r=function(a){var b=_.wH(_.z().Wa,!1),c=_.wH(_.z().Xc,!1);b=_.W(b,"",-6);a.La(".text-container{pointer-events:none;"+(_.X2r.has("POUY7e")?"position:absolute;":"")+(_.X2r.has("POUY7e")?"":"position:relative")+"}");a.La(".spcht{font-weight:normal;line-height:1.2;opacity:0;pointer-events:none;position:absolute;text-align:left;"+(_.TH("font-smoothing",1)+
":antialiased;transition:opacity .1s ease-in,margin-left .5s ease-in,top 0s linear 0.218s;"+(_.X2r.has("POUY7e")?"left:-44px;top:-.2em;margin-left:44px;":"")+(!_.X2r.has("Ftxme")&&_.X2r.has("POUY7e")?"font-size:32px;width:460px;":"")+(_.X2r.has("Ftxme")&&_.X2r.has("POUY7e")?"font-size:28px;width:300px;":"")+(_.X2r.has("POUY7e")?"":"font-size:27px;left:7px;top:.2em;width:490px;margin-left:32px")+"}"));a.La(".s2fp .spcht{margin-left:0;opacity:1;transition:opacity .5s ease-out,margin-left .5s ease-out}");
a.La(".spchta{color:"+b+";cursor:pointer;font-size:"+_.W(c,"",-11)+";font-weight:500;pointer-events:auto;text-decoration:underline}");a.La(".spch-2l.spcht,.spch-3l.spcht,.spch-4l.spcht{transition:top 0.218s ease-out}");a.La(".spch-2l.spcht{top:-.6em}");a.La(".spch-3l.spcht{top:-1.3em}");a.La(".spch-4l.spcht{top:-1.7em}");a.La(".s2fp .spch-5l.spcht{"+(_.X2r.has("POUY7e")?"top:-2.5em;":"")+(_.X2r.has("POUY7e")?"":"font-size:24px;top:-1.7em;transition:font-size 0.218s ease-out")+"}");return""},Y2r=function(a){a.ka(b3r)||
a.Na(b3r,{},$2r,a3r)},b3r="t-MpB9j-pDA3U";var c3r=function(){return""},d3r=function(){return""},e3r=function(){return""},f3r=function(){return!0},g3r=function(){return!1},j3r=function(a,b){h3r(a);return i3r(a,b.ARc,b.ELc)},k3r=function(a,b){h3r(a);var c=b.ARc,d=b.ELc;b="<div"+_.Y("text-container ")+_.Z("")+_.X("")+">";a=i3r(a,c,d);return _.v(b+(a+"</div>"))},i3r=function(a,b,c){return Z2r(a)+"<span"+_.Y("spcht ")+_.Z("color:"+_.V(_.EH(a.isRtl()?_.BH("color",b):b))+";")+_.X(' id="spchi"')+"></span><span"+_.Y("spcht ")+_.Z("color:"+_.V(_.EH(a.isRtl()?
_.BH("color",c):c))+";")+_.X(' id="spchf"')+"></span>"},h3r=function(a){a.ka(l3r)||(a.Na(l3r,{ARc:0,ELc:1},j3r,k3r,f3r,g3r,"",c3r,"text-container ",d3r,"",e3r),Y2r(a))},l3r="t-QB6f6FXn-2c";var m3r=function(){_.wH(_.z().Wa,!1);return""},n3r=function(){_.wH(_.z().Wa,!1);return""},o3r=function(){_.wH(_.z().Wa,!1);return""},p3r=function(){_.wH(_.z().Wa,!1);return!0},q3r=function(){_.wH(_.z().Wa,!1);return!1},t3r=function(a){r3r(a);return s3r(a)},u3r=function(a){r3r(a);_.wH(_.z().Wa,!1);a=s3r(a);return _.v(a)},s3r=function(a){var b=_.wH(_.z().Wa,!1),c=_.W(b,"",-5),d=_.W(b,"",-1);b=T2r(a)+"<button"+_.Y("close-button ")+_.Z("")+_.X(' id="spchx" aria-label="'+_.KH(O2r())+'"')+">&times;</button><div"+
_.Y("spchc ")+_.Z("")+_.X(' id="spchc"')+"><div"+_.Y("inner-container ")+_.Z("")+_.X("")+">";c="<div"+_.Y("text-container ")+_.Z("")+_.X("")+">"+i3r(a,c,d)+"</div>";b=b+c+"</div>";a="<div"+_.Y("permission-bar ")+_.Z("")+_.X("")+">"+E2r(a)+"</div>";b+=a;return b+"</div>"},r3r=function(a){a.ka(v3r)||(a.Na(v3r,{},t3r,u3r,p3r,q3r,"",m3r,"",n3r,"",o3r),D2r(a),N2r(a),S2r(a),h3r(a))},v3r="t-axpif1G9qm0";var UV=-1,a2r,j2r=0,v1r,$1r,d2r,N1r,b2r,VV,e2r,l2r=!1,w3r={};
_.Ee("spch",(w3r.init=function(a){N1r=a.hl;var b=a.mb,c=a.fp,d=_.Pc("spch"),e;if(e=b){if(d){e=new _.hI;r3r(e);var f="";_.wH(_.z().Wa,!1);var g=s3r(e),h=e.Ae();""!==h&&(f+=" <style>"+h+"</style>");f+=g;e.Ba();e=_.v(f);_.hd(d,e);e=!0}else e=!1;e=!e}if(e)M1r();else{if(e=!!window.webkitSpeechRecognition)k1r=b,V1r=c,D1r(),H1r=o2r,b&&p2r&&(E1r=p2r,_.Zd("fpstate",F1r)),(b=(V1r?!!B1r:!0)&&!!C1r&&!!x1r&&!!n1r())&&!(b=k1r)&&(q2r=_.Pc("spchb"),h1r=_.Pc("spchl"),b=!(!q2r||!h1r)),e=b;e?(-1===UV&&(_.Sd(window,
"keydown",J1r),_.nS(_.qS.dKb,K1r),_.nS(_.qS.wqc,K1r),_.nS(_.qS.vqc,L1r)),s1r={tU:a.lm,ready:a.rm,MTc:a.nt,waiting:a.iw,Kuc:a.ae,lTa:a.ne,VPc:a.lu,WWc:a.pe,NTc:a.nv},UV=1,U1r(),W1r(),d&&_.wc(d,"clicked")&&K1r(l2r)):M1r()}},w3r));
_.n();
}catch(e){_._DumpException(e)}
try{
var S0k,Q0k,R0k,U0k;S0k=function(a,b){if(_.Cf(a,"preTranslated"))Q0k(b,"-origindiv");else if(_.Cf(a,"translated"))Q0k(b,"-transdiv");else return R0k(a,b)};_.T0k=function(a){_.Mm(a,"translated","true")};Q0k=function(a,b){var c=a.full,d=_.nl(c),e=""!==a.title?a.title:null;a=_.Pc(a.snippet);var f=_.nl(c+b),g=_.nl(c+"-origLink");c=_.nl(c+"-transLink");U0k(c);U0k(g);U0k(f);c=_.t.Gd(f);e&&(f=_.nl(e),b=_.nl(e+b),_.t.kb(b,c),_.t.kb(f,!c));a?(_.t.kb(d,!1),_.t.kb(a,!c)):_.t.kb(d,!c)};
R0k=function(a,b){if(!_.V0k){_.V0k=!0;_.Ld().Cc("ved",b.ved).log();var c=b.source.substring(0,2),d=b.target.substring(0,2),e=b.full,f=""!==b.title?b.title:null,g=b.key,h=_.nl(e),m=b.keepSnippet,r=b.snippitClassPrefix,u=h.cloneNode(!0);u.id=e+"-transdiv";_.t.kb(u,!1);_.ge(h).appendChild(u);var w=_.sl(r+"__translate-span",u);_.Ll(w);w=new _.W0k;var A=[u];if(f){var D=_.nl(f),I=D.cloneNode(!0);I.id=f+"-transdiv";_.t.kb(I,!1);_.Il(I,D);A.push(I)}return w.send("rv"===g?_.X0k:"pr"===g?_.Y0k:"",c,d,A).then(function(O){var Q=
_.Pc(b.snippet);Q&&(m?_.t.kb(Q,!1):_.Ll(Q));_.t.kb(h,!1);_.t.kb(u,!0);_.hd(u,O[0]);if(f){Q=_.nl(f);var U=_.nl(f+"-transdiv");_.t.kb(Q,!1);_.t.kb(U,!0);_.hd(U,O[1])}m||(O=_.sl(r+"__translate-span",h),_.Ll(O));O=_.nl(e+"-transLink");_.t.kb(O,!1);O=_.nl(e+"-origLink");_.t.kb(O,!0);_.T0k(a);_.V0k=!1})}};U0k=function(a){_.t.kb(a,!_.t.Gd(a))};_.Z0k=new _.Am;_.W0k=function(){this.ka=_.Gc(_.Z0k)};_.W0k.prototype.send=function(a,b,c,d){if(0<this.ka.length)return _.Dm(this.ka,function(r){return r.send()});for(var e=d.length,f=[],g=0,h=0;g<e;g=h){var m=g;h=g+50<e?g+50:e;for(g=[];m<h;m++)g.push(d[m].innerHTML);f.push($0k(a,b,c,g))}return Promise.all(f).then(function(r){var u=[];r=_.Wa(r);for(var w=r.next();!w.done;w=r.next()){w=_.Wa(w.value);for(var A=w.next();!A.done;A=w.next())u.push(_.Ie(A.value))}return u})};
var $0k=function(a,b,c,d){return new Promise(function(e,f){var g=_.mxa({key:a,source:b,target:c,format:"html",q:d});_.vg("https://www.googleapis.com/language/translate/v2",function(h){h=h.target;if(h.Lq()){var m=JSON.parse(h.getResponse()).data.translations;h=[];m=_.Wa(m);for(var r=m.next();!r.done;r=m.next())h.push(r.value.translatedText);e(h)}else f("Translate API failure: "+h.Ww())},"POST",g,{"X-HTTP-Method-Override":"GET"},5E3,!0)})};var a1k;_.X0k="";_.Y0k="";_.V0k=!1;a1k={};_.Ee("tl",(a1k.init=_.ESk("tl",function(a){void 0!==a.rvkey&&(_.X0k=a.rvkey);void 0!==a.prkey&&(_.Y0k=a.prkey);_.NS("tl",{tr:S0k},_.OS("tl"))}),a1k));
}catch(e){_._DumpException(e)}
try{
_.l("tl");

_.n();
}catch(e){_._DumpException(e)}
})(this._s);
// Google Inc.